const VERSION='0.8.0-dev';
const P={
  motorboat:{label:'Motorboot',functions:['Skipper','Crew','Gast'],usage:[['Ausfahrt',0],['Törn',1],['Wasserski',0]],events:['Schleuse','Bewegliche Brücke','Hebewerk','Peilung / Landmarke','Besondere Begegnung','Wetter','Wetteränderung','Technische Beobachtung','Freie Notiz'],stays:['Angelegt','Vor Anker','Mooring'],actions:['Kontrolle','Ablegen','Ereignis','Anlegen / Ankern']},
  motorhome:{label:'Wohnmobil',functions:['Fahrer','Beifahrer','Gast'],usage:[['Tagesausflug',0],['Kurztrip',1],['Urlaub',1]],events:['Fähre','Besondere Begegnung','Wetter','Wetteränderung','Technische Beobachtung','Freie Notiz'],stays:['Stellplatz','Campingplatz','Freier Stellplatz'],actions:['Kontrolle','Abfahrt','Ereignis','Ankunft / Aufenthalt']}
};
const V=[{id:'karoshi',name:'Karõshi',profile:'motorboat',engines:['Motor 1 / BB','Motor 2 / STB']},{id:'womo',name:'Wohnmobil',profile:'motorhome'}];
let S={view:'login',stack:[],vehicle:null,usage:null,day:null,editVehicleId:null,configVehicleId:null,editPersonId:null,personDetailId:null,editAreaId:null,areaDetailId:null,usagePeople:null};
const app=document.querySelector('#app'),bar=document.querySelector('#bar'),title=document.querySelector('#title'),sub=document.querySelector('#sub');
function head(t,s=''){bar.hidden=false;title.textContent=t;sub.textContent=s}
function go(v){S.stack.push(S.view);S.view=v;render()}
function back(){if(S.stack.length){S.view=S.stack.pop();render();return}if(S.view!=='main'){S.view='main';render()}}
function show(v){if(S.view===v)return;go(v)}
function esc(v=''){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){return v?String(v).slice(0,10):''}
function rerenderKeepPosition(anchor){
  const y=window.scrollY, view=S.view;
  render();
  let tries=0;
  const timer=setInterval(()=>{
    tries++;
    if(S.view!==view){clearInterval(timer);return}
    const el=anchor?document.getElementById(anchor):null;
    if(el){el.scrollIntoView({block:'start'});window.scrollBy(0,-10);clearInterval(timer);return}
    if(tries>=40){window.scrollTo(0,y);clearInterval(timer)}
  },100);
}

function render(){({login,main,start,vehicle,usage,setup,cockpit,event,stay,dayend,history:usageHistory,configuration,vehiclesconfig,vehicleedit,vehicleconfigure,usagecatalog,places,persons,personedit,persondetail,areas,areaedit,areadetail,travelcheck,m365setup,workshop,lending,settings}[S.view]||placeholder)()}
function login(){bar.hidden=true;app.innerHTML=`<div class="login"><div class="card"><div class="brand">Fahrzeugplattform</div><p class="muted">Version ${VERSION}</p><div class="field"><label>Nutzer</label><input value="Admin"></div><div class="field"><label>Passwort</label><input type="password" value="admin"></div><button class="primary" onclick="S.stack=[];S.view='main';render()">Anmelden</button></div></div>`}
function main(){S.stack=[];head('Fahrzeugplattform','Admin');app.innerHTML=`<div class="grid">${[['Start','start'],['Konfiguration','configuration'],['Werkstatt','workshop'],['Verleihmodus','lending']].map(x=>`<button class="menu" onclick="go('${x[1]}')"><b>${x[0]}</b></button>`).join('')}</div>`}
function configuration(){head('Konfiguration','Stammdaten und Grundlagen');app.innerHTML=`<div class="grid"><button class="menu" onclick="go('vehiclesconfig')"><b>Fahrzeuge</b><span class="muted">Stammdaten, Ausstattung, Nutzungsarten, Kontrollen, Kosten</span></button><button class="menu" onclick="go('usagecatalog')"><b>Nutzungsarten</b><span class="muted">Zentraler, erweiterbarer Stamm</span></button><button class="menu" onclick="go('places')"><b>Orte / Standorte</b><span class="muted">Ortschaften, Häfen, Stellplätze und GPS-Grundlage</span></button><button class="menu" onclick="go('persons')"><b>Personen</b><span class="muted">Rollen, Funktionen, Nachweise</span></button><button class="menu" onclick="go('areas')"><b>Gebiete / Reviere</b><span class="muted">Länder, Reviere, Anforderungen</span></button><button class="menu" onclick="go('travelcheck')"><b>Reisecheck</b><span class="muted">Soll/Ist vor einer Reise</span></button><button class="menu" onclick="go('m365setup')"><b>Microsoft 365 Setup</b><span class="muted">SharePoint Phase 1 automatisch anlegen</span></button></div>`}

async function getCloud(){const tok=FPAuth.token(),siteUrl=localStorage.getItem('fp_sp_site')||'';if(!tok)throw new Error('Microsoft-Verbindung fehlt. Bitte unter Einstellungen → Microsoft 365 Setup anmelden.');if(!siteUrl)throw new Error('SharePoint-Site fehlt. Bitte unter Microsoft 365 Setup die Site verbinden.');const api=new FPGraphSetup(tok,siteUrl,{lists:[]});await api.resolveSite();return api}
async function list(api,name){return api.listItemsByName(name)}
function failBox(e,backTo='m365setup'){app.innerHTML=`<div class="card status-stop"><b>Daten konnten nicht geladen werden</b><p>${esc(e.message)}</p><button onclick="go('${backTo}')">${backTo==='m365setup'?'Microsoft 365 Setup öffnen':'Zurück'}</button></div>`}

async function vehiclesconfig(){head('Fahrzeuge','Stammdaten und Konfiguration');app.innerHTML='<div class="card">Fahrzeuge werden aus SharePoint geladen …</div>';try{const api=await getCloud(),items=await list(api,'Fahrzeuge');app.innerHTML=`<div class="card"><button class="primary" onclick="S.editVehicleId=null;go('vehicleedit')">Neues Fahrzeug</button></div>`+(items.length?items.map(x=>`<button class="menu vehicle-row" onclick="S.editVehicleId='${x.id}';go('vehicleedit')"><b>${esc(x.fields.Fahrzeugname||x.fields.Title||'Ohne Name')}</b><span class="muted">${esc(x.fields.Profil||x.fields.Fahrzeugtyp||'')} · ${esc(x.fields.Hersteller||'')} ${esc(x.fields.Modell||'')}</span></button>`).join(''):'<div class="card">Noch kein Fahrzeug in SharePoint angelegt.</div>')}catch(e){failBox(e)}}
async function vehicleedit(){head(S.editVehicleId?'Fahrzeug bearbeiten':'Neues Fahrzeug','Stammdaten · SharePoint');let f={};try{if(S.editVehicleId){const api=await getCloud(),x=await api.getItemByName('Fahrzeuge',S.editVehicleId);f=x.fields||{}}}catch(e){failBox(e);return}app.innerHTML=`<div class="card"><div class="field"><label>Fahrzeugname *</label><input id="fvName" value="${esc(f.Fahrzeugname||f.Title||'')}"></div><div class="field"><label>Profil *</label><select id="fvProfil"><option ${f.Profil==='Motorboot'?'selected':''}>Motorboot</option><option ${f.Profil==='Wohnmobil'?'selected':''}>Wohnmobil</option></select></div><div class="field"><label>Fahrzeugtyp *</label><input id="fvTyp" value="${esc(f.Fahrzeugtyp||'')}"></div><div class="field"><label>Hersteller</label><input id="fvHersteller" value="${esc(f.Hersteller||'')}"></div><div class="field"><label>Modell</label><input id="fvModell" value="${esc(f.Modell||'')}"></div><div class="field"><label>Baujahr</label><input id="fvBaujahr" type="number" value="${esc(f.Baujahr??'')}"></div><div class="field"><label>Kennzeichen / Registrierung</label><input id="fvKennz" value="${esc(f.KennzeichenRegistrierung||'')}"></div><label><input id="fvAktiv" type="checkbox" ${f.Aktiv===false?'':'checked'}> Aktiv</label><div class="actions"><button class="primary" onclick="saveVehicle(false)">Stammdaten speichern</button>${S.editVehicleId?`<button onclick="S.configVehicleId='${S.editVehicleId}';go('vehicleconfigure')">Ausrüsten / konfigurieren</button>`:''}</div></div>`}
async function saveVehicle(openConfig=false){const name=fvName.value.trim(),typ=fvTyp.value.trim();if(!name||!typ){alert('Fahrzeugname und Fahrzeugtyp sind Pflichtfelder.');return}const fields={Title:name,DatenraumId:'default',Fahrzeugname:name,Fahrzeugtyp:typ,Profil:fvProfil.value,Hersteller:fvHersteller.value.trim(),Modell:fvModell.value.trim(),KennzeichenRegistrierung:fvKennz.value.trim(),Aktiv:fvAktiv.checked};if(fvBaujahr.value)fields.Baujahr=Number(fvBaujahr.value);try{const api=await getCloud();let id=S.editVehicleId;if(id)await api.updateItemByName('Fahrzeuge',id,fields);else{id=String((await api.createItemByName('Fahrzeuge',fields)).id);S.editVehicleId=id}if(openConfig){S.configVehicleId=id;go('vehicleconfigure')}else{S.stack=[];S.view='vehiclesconfig';render()}}catch(e){alert('Speichern nicht möglich: '+e.message)}}

async function vehicleconfigure(){head('Fahrzeug konfigurieren','Ausstattung und Grundlagen');app.innerHTML='<div class="card">Konfiguration wird geladen …</div>';try{
const api=await getCloud(),v=await api.getItemByName('Fahrzeuge',S.configVehicleId),f=v.fields||{},
[components,features,maps,types,checks,costs]=await Promise.all([list(api,'Komponenten'),list(api,'Fahrzeugmerkmale'),list(api,'FahrzeugNutzungsarten'),list(api,'Nutzungsarten'),list(api,'FahrzeugPruefpunkte'),list(api,'Ausgaben')]);
const cs=components.filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)),fs=features.filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)),
ms=maps.filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)),ps=checks.filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)),
ks=costs.filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)&&!x.fields.NutzungId);
const profile=f.Profil||'Motorboot', enabled=new Set(ms.filter(x=>x.fields.Aktiv!==false).map(x=>String(x.fields.NutzungsartId)));
const availableTypes=types.filter(x=>x.fields.Profil===profile && x.fields.Aktiv!==false);
const rowActions=(listName,x,anchor,hasActive=true)=>`<div class="row-actions">${hasActive?`<button onclick="toggleConfigItem('${listName}','${x.id}',${x.fields.Aktiv===false?'true':'false'},'${anchor}')">${x.fields.Aktiv===false?'Aktivieren':'Inaktiv'}</button>`:''}<button class="danger-lite" onclick="deleteConfigItem('${listName}','${x.id}','${anchor}')">Löschen</button></div>`;
const costInterval=x=>{const a=x.fields.IntervallArt||'Einmalig';return a==='Alle X Monate'?`alle ${x.fields.IntervallWert||'?'} Monate`:a.toLowerCase()};
app.innerHTML=`<div class="card"><b>${esc(f.Fahrzeugname||f.Title)}</b><p class="muted">${esc(profile)} · ${esc(f.Hersteller||'')} ${esc(f.Modell||'')}</p></div>
<div class="card" id="sec-components"><div class="section first">Komponenten / Ausstattung</div>${cs.length?cs.map(x=>`<div class="line"><div><b>${esc(x.fields.Name)}</b><div class="muted">${esc(x.fields.KomponentenTyp||x.fields.Typ||'')}${x.fields.Aktiv===false?' · inaktiv':''}</div></div>${rowActions('Komponenten',x,'sec-components')}</div>`).join(''):'<p class="muted">Noch keine Komponenten.</p>'}<div class="grid compact"><div class="field"><label>Typ</label><input id="vcType" placeholder="Motor, Tank, Batterie …"></div><div class="field"><label>Name</label><input id="vcName" placeholder="z. B. Motor BB"></div></div><div class="field"><label>Unterkomponente von</label><select id="vcParent"><option value="">– keine –</option>${cs.filter(x=>x.fields.Aktiv!==false).map(x=>`<option value="${x.id}">${esc(x.fields.Name)}</option>`).join('')}</select></div><button onclick="addVehicleComponent()">Komponente hinzufügen</button></div>
<div class="card" id="sec-features"><div class="section first">Fahrzeugmerkmale / Einheiten / GPS / Navigation</div>${fs.length?fs.map(x=>`<div class="line"><div><b>${esc(x.fields.Merkmal)}</b><div class="muted">${esc(x.fields.WertText||x.fields.WertZahl||'')} ${esc(x.fields.Einheit||'')}${x.fields.Aktiv===false?' · inaktiv':''}</div></div>${rowActions('Fahrzeugmerkmale',x,'sec-features')}</div>`).join(''):'<p class="muted">Noch keine Merkmale.</p>'}<div class="grid compact"><div class="field"><label>Merkmal</label><input id="vmName" placeholder="z. B. GPS-Intervall"></div><div class="field"><label>Wert</label><input id="vmValue"></div></div><div class="field"><label>Einheit (optional)</label><input id="vmUnit"></div><button onclick="addVehicleFeature()">Merkmal hinzufügen</button></div>
<div class="card" id="sec-usages"><div class="section first">Aktivierte Nutzungsarten</div>${availableTypes.length?availableTypes.map(t=>`<label class="checkrow"><input type="checkbox" data-usage-id="${t.id}" ${enabled.has(String(t.id))?'checked':''}> ${esc(t.fields.Name||t.fields.Title)}</label>`).join(''):'<p class="muted">Für dieses Profil gibt es noch keine aktive Nutzungsart im Stamm.</p>'}<div class="actions"><button onclick="saveVehicleUsageTypesV2()">Nutzungsarten speichern</button><button onclick="go('usagecatalog')">Nutzungsarten-Stamm öffnen</button></div></div>
<div class="card" id="sec-checks"><div class="section first">Kontrollpunkte / Intervalle</div>${ps.length?ps.map(x=>`<div class="line"><div><b>${esc(x.fields.Name)}</b><div class="muted">${esc(x.fields.IntervallRegel||'ohne Intervall')}${x.fields.Aktiv===false?' · inaktiv':''}</div></div>${rowActions('FahrzeugPruefpunkte',x,'sec-checks')}</div>`).join(''):'<p class="muted">Noch keine Prüfpunkte.</p>'}<div class="grid compact"><div class="field"><label>Prüfpunkt</label><input id="vpName"></div><div class="field"><label>Intervallregel</label><input id="vpRule" placeholder="täglich / 50 h / jährlich"></div></div><button onclick="addVehicleCheckpoint()">Prüfpunkt hinzufügen</button></div>
<div class="card" id="sec-costs"><div class="section first">Allgemeine Fahrzeugkosten</div>${ks.length?ks.map(x=>`<div class="line"><div><b>${esc(x.fields.Kostenart)}</b><div class="muted">${esc(x.fields.Betrag)} ${esc(x.fields.Waehrung||'EUR')} · ${esc(costInterval(x))}${x.fields.NaechsteFaelligkeit?' · nächste '+fmtDate(x.fields.NaechsteFaelligkeit):''}${x.fields.Aktiv===false?' · inaktiv':''}</div></div>${rowActions('Ausgaben',x,'sec-costs')}</div>`).join(''):'<p class="muted">Noch keine allgemeinen Kosten.</p>'}<div class="grid compact"><div class="field"><label>Kostenart</label><input id="vkType" placeholder="Versicherung, Steuer …"></div><div class="field"><label>Betrag</label><input id="vkAmount" type="number" step="0.01"></div></div><div class="grid compact"><div class="field"><label>Intervall</label><select id="vkInterval"><option>Einmalig</option><option>Monatlich</option><option>Alle X Monate</option><option>Jährlich</option></select></div><div class="field"><label>X Monate</label><input id="vkIntervalValue" type="number" min="1" placeholder="z. B. 3"></div></div><div class="grid compact"><div class="field"><label>Startdatum</label><input id="vkStart" type="date"></div><div class="field"><label>Nächste Fälligkeit</label><input id="vkNext" type="date"></div></div><div class="grid compact"><div class="field"><label>Enddatum (optional)</label><input id="vkEnd" type="date"></div><div class="field"><label>Währung</label><input id="vkCurrency" value="EUR"></div></div><button onclick="addVehicleCost()">Kostenart anlegen</button></div>`;
}catch(e){failBox(e)}}
async function addVehicleComponent(){if(!vcType.value.trim()||!vcName.value.trim())return alert('Typ und Name eingeben.');try{const api=await getCloud();await api.createItemByName('Komponenten',{FahrzeugId:String(S.configVehicleId),ParentKomponenteId:vcParent.value||'',KomponentenTyp:vcType.value.trim(),Name:vcName.value.trim(),Aktiv:true});rerenderKeepPosition('sec-components')}catch(e){alert(e.message)}}
async function addVehicleFeature(){if(!vmName.value.trim())return alert('Merkmal eingeben.');const raw=vmValue.value.trim(),num=raw!==''&&!Number.isNaN(Number(raw))?Number(raw):null;try{const api=await getCloud(),fields={FahrzeugId:String(S.configVehicleId),Merkmal:vmName.value.trim(),WertText:num===null?raw:'',Einheit:vmUnit.value.trim(),Aktiv:true};if(num!==null)fields.WertZahl=num;await api.createItemByName('Fahrzeugmerkmale',fields);rerenderKeepPosition('sec-features')}catch(e){alert(e.message)}}
async function saveVehicleUsageTypes(profile){try{const api=await getCloud();let types=await list(api,'Nutzungsarten'),maps=await list(api,'FahrzeugNutzungsarten');const checks=[...document.querySelectorAll('[data-usage]')];for(let i=0;i<checks.length;i++){const c=checks[i],name=c.dataset.usage;let t=types.find(x=>x.fields.Name===name&&x.fields.Profil===profile);if(!t&&c.checked){t=await api.createItemByName('Nutzungsarten',{Title:name,Profil:profile,Name:name,Aktiv:true});types.push(t)}if(!t)continue;let m=maps.find(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)&&String(x.fields.NutzungsartId)===String(t.id));if(m)await api.updateItemByName('FahrzeugNutzungsarten',m.id,{Aktiv:c.checked,Sortierung:i+1});else if(c.checked)await api.createItemByName('FahrzeugNutzungsarten',{FahrzeugId:String(S.configVehicleId),NutzungsartId:String(t.id),Aktiv:true,Sortierung:i+1})}rerenderKeepPosition('sec-usages')}catch(e){alert(e.message)}}
async function saveVehicleUsageTypesV2(){try{
 const api=await getCloud(),maps=await list(api,'FahrzeugNutzungsarten'),checks=[...document.querySelectorAll('[data-usage-id]')];
 for(let i=0;i<checks.length;i++){const c=checks[i],id=String(c.dataset.usageId);let m=maps.find(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)&&String(x.fields.NutzungsartId)===id);
   if(m)await api.updateItemByName('FahrzeugNutzungsarten',m.id,{Aktiv:c.checked,Sortierung:i+1});
   else if(c.checked)await api.createItemByName('FahrzeugNutzungsarten',{FahrzeugId:String(S.configVehicleId),NutzungsartId:id,Aktiv:true,Sortierung:i+1});
 }
 rerenderKeepPosition('sec-usages');
}catch(e){alert(e.message)}}
async function toggleConfigItem(listName,id,newState,anchor){try{const api=await getCloud();await api.updateItemByName(listName,id,{Aktiv:newState});rerenderKeepPosition(anchor)}catch(e){alert(e.message)}}
async function deleteConfigItem(listName,id,anchor){if(!confirm('Diesen Eintrag wirklich löschen? Bei bereits verwendeten historischen Daten besser Inaktiv verwenden.'))return;try{const api=await getCloud();await api.deleteItemByName(listName,id);rerenderKeepPosition(anchor)}catch(e){alert('Löschen nicht möglich: '+e.message)}}

async function addVehicleCheckpoint(){if(!vpName.value.trim())return alert('Prüfpunkt eingeben.');try{const api=await getCloud();await api.createItemByName('FahrzeugPruefpunkte',{FahrzeugId:String(S.configVehicleId),Name:vpName.value.trim(),IntervallRegel:vpRule.value.trim(),Aktiv:true});rerenderKeepPosition('sec-checks')}catch(e){alert(e.message)}}
async function addVehicleCost(){if(!vkType.value.trim()||!vkAmount.value)return alert('Kostenart und Betrag eingeben.');if(vkInterval.value==='Alle X Monate'&&(!vkIntervalValue.value||Number(vkIntervalValue.value)<1))return alert('Bitte Anzahl Monate eingeben.');try{const api=await getCloud(),toIso=v=>v?new Date(v+'T12:00:00').toISOString():null;const fields={FahrzeugId:String(S.configVehicleId),NutzungId:'',BezugTyp:'Fahrzeug',BezugId:String(S.configVehicleId),Kostenart:vkType.value.trim(),Betrag:Number(vkAmount.value),Waehrung:vkCurrency.value.trim()||'EUR',Datum:toIso(vkStart.value)||new Date().toISOString(),Startdatum:toIso(vkStart.value)||new Date().toISOString(),IntervallArt:vkInterval.value,Aktiv:true};if(vkInterval.value==='Alle X Monate')fields.IntervallWert=Number(vkIntervalValue.value);if(vkEnd.value)fields.Enddatum=toIso(vkEnd.value);if(vkNext.value)fields.NaechsteFaelligkeit=toIso(vkNext.value);await api.createItemByName('Ausgaben',fields);rerenderKeepPosition('sec-costs')}catch(e){alert(e.message)}}

async function usagecatalog(){head('Nutzungsarten','Zentraler Stamm');app.innerHTML='<div class="card">Nutzungsarten werden geladen …</div>';try{const api=await getCloud(),rows=await list(api,'Nutzungsarten');app.innerHTML=`<div class="card" id="usage-catalog"><div class="section first">Vorhandene Nutzungsarten</div>${rows.map(x=>`<div class="line"><div><b>${esc(x.fields.Name||x.fields.Title)}</b><div class="muted">${esc(x.fields.Profil)}${x.fields.Aktiv===false?' · inaktiv':''}</div></div><div class="row-actions"><button onclick="toggleConfigItem('Nutzungsarten','${x.id}',${x.fields.Aktiv===false?'true':'false'},'usage-catalog')">${x.fields.Aktiv===false?'Aktivieren':'Inaktiv'}</button><button class="danger-lite" onclick="deleteConfigItem('Nutzungsarten','${x.id}','usage-catalog')">Löschen</button></div></div>`).join('')||'<p class="muted">Noch keine Nutzungsarten.</p>'}<div class="grid compact"><div class="field"><label>Profil</label><select id="ucProfile"><option>Motorboot</option><option>Wohnmobil</option></select></div><div class="field"><label>Nutzungsart</label><input id="ucName" placeholder="z. B. Törn"></div></div><button onclick="addUsageCatalog()">Nutzungsart hinzufügen</button></div>`}catch(e){failBox(e)}}
async function addUsageCatalog(){const n=ucName.value.trim();if(!n)return alert('Nutzungsart eingeben.');try{const api=await getCloud(),all=await list(api,'Nutzungsarten');if(all.some(x=>x.fields.Profil===ucProfile.value&&(x.fields.Name||x.fields.Title||'').toLowerCase()===n.toLowerCase()))return alert('Diese Nutzungsart existiert für das Profil bereits.');await api.createItemByName('Nutzungsarten',{Title:n,Profil:ucProfile.value,Name:n,Aktiv:true});rerenderKeepPosition('usage-catalog')}catch(e){alert(e.message)}}

async function places(){head('Orte / Standorte','Wiederverwendbare Ziele für Planung und Navigation');app.innerHTML='<div class="card">Orte werden geladen …</div>';try{const api=await getCloud(),[orts,sites]=await Promise.all([list(api,'Orte'),list(api,'Standorte')]);const oById=Object.fromEntries(orts.map(o=>[String(o.id),o]));app.innerHTML=`<div class="card" id="sec-places"><div class="section first">Orte</div>${orts.map(o=>`<div class="line"><div><b>${esc(o.fields.Name||o.fields.Title)}</b><div class="muted">${esc(o.fields.Land||'')}${o.fields.Favorit?' · ★ Favorit':''}${o.fields.Aktiv===false?' · inaktiv':''}</div></div><div class="row-actions"><button onclick="toggleConfigItem('Orte','${o.id}',${o.fields.Aktiv===false?'true':'false'},'sec-places')">${o.fields.Aktiv===false?'Aktivieren':'Inaktiv'}</button><button class="danger-lite" onclick="deleteConfigItem('Orte','${o.id}','sec-places')">Löschen</button></div></div>`).join('')||'<p class="muted">Noch keine Orte.</p>'}<div class="grid compact"><div class="field"><label>Ort *</label><input id="plName"></div><div class="field"><label>Land</label><input id="plLand"></div></div><label class="checkrow"><input id="plFav" type="checkbox"> Favorit</label><button onclick="addPlace()">Ort hinzufügen</button></div>
<div class="card" id="sec-sites"><div class="section first">Konkrete Standorte</div>${sites.map(s=>`<div class="line"><div><b>${esc(s.fields.Name||s.fields.Title)}</b><div class="muted">${esc(s.fields.Standorttyp||'Standort')} · ${esc(oById[String(s.fields.OrtId)]?.fields?.Name||'ohne Ort')}${s.fields.Favorit?' · ★ Favorit':''}${s.fields.Aktiv===false?' · inaktiv':''}</div></div><div class="row-actions"><button onclick="toggleConfigItem('Standorte','${s.id}',${s.fields.Aktiv===false?'true':'false'},'sec-sites')">${s.fields.Aktiv===false?'Aktivieren':'Inaktiv'}</button><button class="danger-lite" onclick="deleteConfigItem('Standorte','${s.id}','sec-sites')">Löschen</button></div></div>`).join('')||'<p class="muted">Noch keine Standorte.</p>'}<div class="grid compact"><div class="field"><label>Ort</label><select id="psOrt"><option value="">– ohne Ortszuordnung –</option>${orts.filter(o=>o.fields.Aktiv!==false).map(o=>`<option value="${o.id}">${esc(o.fields.Name||o.fields.Title)}</option>`).join('')}</select></div><div class="field"><label>Standorttyp</label><select id="psType">${['Hafen','Marina','Liegeplatz','Ankerplatz','Mooring','Stellplatz','Campingplatz','Parkplatz','Tankstelle','Werkstatt','Sonstiges'].map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="field"><label>Name *</label><input id="psName"></div><div class="field"><label>Adresse</label><input id="psAddress"></div><label class="checkrow"><input id="psFav" type="checkbox"> Favorit</label><button onclick="addSite()">Standort hinzufügen</button></div>`}catch(e){failBox(e)}}
async function addPlace(){const n=plName.value.trim();if(!n)return alert('Ort eingeben.');try{const api=await getCloud(),all=await list(api,'Orte');const hit=all.find(x=>(x.fields.Name||x.fields.Title||'').trim().toLowerCase()===n.toLowerCase());if(hit)return alert('Dieser Ort existiert bereits. Bitte vorhandenen Ort verwenden.');await api.createItemByName('Orte',{Title:n,Name:n,Land:plLand.value.trim(),Favorit:plFav.checked,Verwendungen:0,Aktiv:true});rerenderKeepPosition('sec-places')}catch(e){alert(e.message)}}
async function addSite(){const n=psName.value.trim();if(!n)return alert('Standortnamen eingeben.');try{const api=await getCloud(),all=await list(api,'Standorte');if(all.some(x=>String(x.fields.OrtId||'')===String(psOrt.value||'')&&(x.fields.Name||x.fields.Title||'').trim().toLowerCase()===n.toLowerCase()))return alert('Dieser Standort ist für den Ort bereits vorhanden.');await api.createItemByName('Standorte',{Title:n,OrtId:psOrt.value||'',Name:n,Standorttyp:psType.value,Adresse:psAddress.value.trim(),Favorit:psFav.checked,Verwendungen:0,Aktiv:true});rerenderKeepPosition('sec-sites')}catch(e){alert(e.message)}}

async function persons(){head('Personen','Rollen, Funktionen und Befähigungen');app.innerHTML='<div class="card">Personen werden geladen …</div>';try{const api=await getCloud(),ps=await list(api,'Personen');app.innerHTML=`<div class="card"><button class="primary" onclick="S.editPersonId=null;go('personedit')">Neue Person</button></div>`+(ps.length?ps.map(p=>`<button class="menu" onclick="S.personDetailId='${p.id}';go('persondetail')"><b>${esc(p.fields.Anzeigename||p.fields.Title||'Ohne Name')}</b><span class="muted">${esc(p.fields.Rolle||'Benutzer')}${p.fields.Aktiv===false?' · inaktiv':''}</span></button>`).join(''):'<div class="card">Noch keine Personen.</div>')}catch(e){failBox(e)}}
async function personedit(){head(S.editPersonId?'Person bearbeiten':'Neue Person','Rolle und Grunddaten');let f={};try{if(S.editPersonId){const api=await getCloud(),x=await api.getItemByName('Personen',S.editPersonId);f=x.fields||{}}}catch(e){failBox(e);return}app.innerHTML=`<div class="card"><div class="field"><label>Anzeigename *</label><input id="peName" value="${esc(f.Anzeigename||f.Title||'')}"></div><div class="field"><label>Rolle</label><select id="peRole">${['Admin','Benutzer','Leiher','Gast'].map(r=>`<option ${f.Rolle===r?'selected':''}>${r}</option>`).join('')}</select></div><label><input id="peActive" type="checkbox" ${f.Aktiv===false?'':'checked'}> Aktiv</label><button class="primary" onclick="savePerson()">Speichern</button></div>`}
async function savePerson(){const n=peName.value.trim();if(!n)return alert('Name eingeben.');try{const api=await getCloud(),fields={Title:n,DatenraumId:'default',Anzeigename:n,Rolle:peRole.value,Aktiv:peActive.checked};let id=S.editPersonId;if(id)await api.updateItemByName('Personen',id,fields);else id=String((await api.createItemByName('Personen',fields)).id);S.personDetailId=id;S.stack=[];S.view='persondetail';render()}catch(e){alert(e.message)}}
async function ensureQualificationCatalog(api){let cat=await list(api,'BefaehigungsKatalog');if(cat.length)return cat;const defaults=[['AM','Führerschein'],['A1','Führerschein'],['A2','Führerschein'],['A','Führerschein'],['B','Führerschein'],['BE','Führerschein'],['C1','Führerschein'],['C1E','Führerschein'],['C','Führerschein'],['CE','Führerschein'],['D1','Führerschein'],['D1E','Führerschein'],['D','Führerschein'],['DE','Führerschein'],['L','Führerschein'],['T','Führerschein'],['SBF Binnen','Bootsführerschein'],['SBF See','Bootsführerschein'],['UBI','Funkzeugnis'],['SRC','Funkzeugnis'],['LRC','Funkzeugnis'],['Bodenseeschifferpatent','Patent']];for(const [name,catg] of defaults)await api.createItemByName('BefaehigungsKatalog',{Title:name,Name:name,Kategorie:catg,Land:'Deutschland',Aktiv:true});return list(api,'BefaehigungsKatalog')}
async function persondetail(){head('Person','Funktionen und Nachweise');app.innerHTML='<div class="card">Person wird geladen …</div>';try{const api=await getCloud(),p=await api.getItemByName('Personen',S.personDetailId),[fs,qs,cat]=await Promise.all([list(api,'PersonFunktionen'),list(api,'Befaehigungen'),ensureQualificationCatalog(api)]),ownF=fs.filter(x=>String(x.fields.PersonId)===String(S.personDetailId)),ownQ=qs.filter(x=>String(x.fields.PersonId)===String(S.personDetailId));app.innerHTML=`<div class="card"><b>${esc(p.fields.Anzeigename||p.fields.Title)}</b><div class="muted">Rolle: ${esc(p.fields.Rolle||'Benutzer')}</div><div class="actions"><button onclick="S.editPersonId='${S.personDetailId}';go('personedit')">Person bearbeiten</button></div></div><div class="card" id="person-functions"><div class="section first">Mögliche Funktionen</div>${ownF.map(x=>`<div class="line"><b>${esc(x.fields.Funktion)}</b></div>`).join('')||'<p class="muted">Noch keine Funktionen.</p>'}<div class="field"><label>Funktion hinzufügen</label><select id="pfFunction">${['Skipper','Fahrer','Crew','Beifahrer','Gast'].map(x=>`<option>${x}</option>`).join('')}</select></div><button onclick="addPersonFunction()">Funktion hinzufügen</button></div><div class="card" id="person-quals"><div class="section first">Lizenzen / Patente / Nachweise</div>${ownQ.map(q=>`<div class="line"><div><b>${esc(q.fields.Art)}</b><div class="muted">${q.fields.Vorhanden===false?'nicht vorhanden':'vorhanden'}${q.fields.GueltigBis?' · bis '+fmtDate(q.fields.GueltigBis):''}</div></div></div>`).join('')||'<p class="muted">Noch keine Nachweise.</p>'}<div class="field"><label>Nachweis auswählen</label><select id="pqArt">${cat.filter(x=>x.fields.Aktiv!==false).map(x=>`<option>${esc(x.fields.Name||x.fields.Title)}</option>`).join('')}</select></div><div class="grid compact"><div class="field"><label>Nummer</label><input id="pqNum"></div><div class="field"><label>Aussteller</label><input id="pqIssuer"></div></div><div class="grid compact"><div class="field"><label>Gültig von</label><input id="pqFrom" type="date"></div><div class="field"><label>Gültig bis</label><input id="pqTo" type="date"></div></div><label class="checkrow"><input id="pqPresent" type="checkbox" checked> Vorhanden / nachgewiesen</label><button onclick="addQualification()">Nachweis hinzufügen</button><hr><div class="grid compact"><div class="field"><label>Weiteren Katalogeintrag ergänzen</label><input id="qcName" placeholder="z. B. kanadischer Bootsführerschein"></div><div class="field"><label>Kategorie</label><select id="qcCat"><option>Führerschein</option><option>Bootsführerschein</option><option>Funkzeugnis</option><option>Patent</option><option>Sonstiges</option></select></div></div><div class="field"><label>Land / Geltungsbereich</label><input id="qcLand"></div><button onclick="addQualificationCatalog()">Zum Auswahlkatalog hinzufügen</button></div>`}catch(e){failBox(e)}}
async function addPersonFunction(){try{const api=await getCloud(),all=await list(api,'PersonFunktionen');if(all.some(x=>String(x.fields.PersonId)===String(S.personDetailId)&&x.fields.Funktion===pfFunction.value))return alert('Funktion ist bereits hinterlegt.');await api.createItemByName('PersonFunktionen',{PersonId:String(S.personDetailId),Funktion:pfFunction.value,Aktiv:true});rerenderKeepPosition('person-functions')}catch(e){alert(e.message)}}
async function addQualification(){if(!pqArt.value.trim())return alert('Nachweis auswählen.');try{const api=await getCloud(),f={PersonId:String(S.personDetailId),Art:pqArt.value.trim(),Vorhanden:pqPresent.checked,Nummer:pqNum.value.trim(),Aussteller:pqIssuer.value.trim(),GeprueftAm:new Date().toISOString()};if(pqFrom.value)f.GueltigVon=new Date(pqFrom.value+'T12:00:00').toISOString();if(pqTo.value)f.GueltigBis=new Date(pqTo.value+'T12:00:00').toISOString();f.Aktiv=true;await api.createItemByName('Befaehigungen',f);rerenderKeepPosition('person-quals')}catch(e){alert(e.message)}}
async function addQualificationCatalog(){const n=qcName.value.trim();if(!n)return alert('Bezeichnung eingeben.');try{const api=await getCloud(),all=await list(api,'BefaehigungsKatalog');if(all.some(x=>(x.fields.Name||x.fields.Title||'').toLowerCase()===n.toLowerCase()))return alert('Dieser Eintrag existiert bereits.');await api.createItemByName('BefaehigungsKatalog',{Title:n,Name:n,Kategorie:qcCat.value,Land:qcLand.value.trim(),Aktiv:true});rerenderKeepPosition('person-quals')}catch(e){alert(e.message)}}

async function areas(){head('Gebiete / Reviere','Hierarchie und Anforderungen');app.innerHTML='<div class="card">Gebiete werden geladen …</div>';try{const api=await getCloud(),gs=await list(api,'Gebiete');app.innerHTML=`<div class="card"><button class="primary" onclick="S.editAreaId=null;go('areaedit')">Neues Gebiet / Revier</button></div>`+(gs.length?gs.map(g=>`<button class="menu" onclick="S.areaDetailId='${g.id}';go('areadetail')"><b>${esc(g.fields.Name||g.fields.Title)}</b><span class="muted">${esc(g.fields.Gebietstyp||'Gebiet')}${g.fields.ParentGebietId?' · untergeordnet':''}</span></button>`).join(''):'<div class="card">Noch keine Gebiete.</div>')}catch(e){failBox(e)}}
async function areaedit(){head(S.editAreaId?'Gebiet bearbeiten':'Neues Gebiet / Revier','Hierarchische Struktur');let f={},parents=[];try{const api=await getCloud();parents=await list(api,'Gebiete');if(S.editAreaId){const x=await api.getItemByName('Gebiete',S.editAreaId);f=x.fields||{}}}catch(e){failBox(e);return}app.innerHTML=`<div class="card"><div class="field"><label>Name *</label><input id="aeName" value="${esc(f.Name||f.Title||'')}"></div><div class="field"><label>Gebietstyp</label><select id="aeType">${['Land','Region','Revier','Teilgebiet','Sondergebiet'].map(t=>`<option ${f.Gebietstyp===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Übergeordnetes Gebiet</label><select id="aeParent"><option value="">– keines –</option>${parents.filter(x=>String(x.id)!==String(S.editAreaId||'')).map(x=>`<option value="${x.id}" ${String(f.ParentGebietId||'')===String(x.id)?'selected':''}>${esc(x.fields.Name||x.fields.Title)}</option>`).join('')}</select></div><label><input id="aeActive" type="checkbox" ${f.Aktiv===false?'':'checked'}> Aktiv</label><button class="primary" onclick="saveArea()">Speichern</button></div>`}
async function saveArea(){const n=aeName.value.trim();if(!n)return alert('Name eingeben.');try{const api=await getCloud(),fields={Title:n,Name:n,Gebietstyp:aeType.value,ParentGebietId:aeParent.value||'',Aktiv:aeActive.checked};let id=S.editAreaId;if(id)await api.updateItemByName('Gebiete',id,fields);else id=String((await api.createItemByName('Gebiete',fields)).id);S.areaDetailId=id;S.stack=[];S.view='areadetail';render()}catch(e){alert(e.message)}}
async function areadetail(){head('Gebiet / Revier','Anforderungen');app.innerHTML='<div class="card">Anforderungen werden geladen …</div>';try{const api=await getCloud(),g=await api.getItemByName('Gebiete',S.areaDetailId),rs=await list(api,'GebietsAnforderungen'),own=rs.filter(x=>String(x.fields.GebietId)===String(S.areaDetailId));app.innerHTML=`<div class="card"><b>${esc(g.fields.Name||g.fields.Title)}</b><div class="muted">${esc(g.fields.Gebietstyp)}</div><div class="actions"><button onclick="S.editAreaId='${S.areaDetailId}';go('areaedit')">Gebiet bearbeiten</button></div></div><div class="card" id="area-reqs"><div class="section first">Anforderungen</div>${own.length?own.map(r=>`<div class="line"><div><b>${esc(r.fields.SubjektTyp)} · ${esc(r.fields.Verkehrsart)}</b><div>${esc(r.fields.Anforderung)}</div><div class="muted">${r.fields.Pflicht?'Pflicht · ':''}${esc(r.fields.QuelleTyp||'')}${r.fields.GeprueftAm?' · geprüft '+fmtDate(r.fields.GeprueftAm):''}</div></div></div>`).join(''):'<p class="muted">Noch keine Anforderungen hinterlegt.</p>'}<div class="grid compact"><div class="field"><label>Subjekt</label><select id="arSubject"><option>Person</option><option>Fahrzeug</option><option>Tier</option></select></div><div class="field"><label>Verkehrsart</label><select id="arMode"><option>Strasse</option><option>Binnen</option><option>See</option><option>Sonderrevier</option></select></div></div><div class="field"><label>Anforderung *</label><textarea id="arText"></textarea></div><div class="grid compact"><div class="field"><label>Quellentyp</label><input id="arSourceType" placeholder="Behörde, Nutzerrecherche …"></div><div class="field"><label>Geprüft am</label><input id="arChecked" type="date"></div></div><div class="field"><label>Quelle / Link / Referenz</label><textarea id="arSource"></textarea></div><label class="checkrow"><input id="arMandatory" type="checkbox" checked> Pflichtanforderung</label><button onclick="addAreaRequirement()">Anforderung hinzufügen</button><p class="muted">Planungshilfe, keine rechtsverbindliche Auskunft. Anforderungen müssen aktuell geprüft werden.</p></div>`}catch(e){failBox(e)}}
async function addAreaRequirement(){if(!arText.value.trim())return alert('Anforderung eingeben.');try{const api=await getCloud(),f={GebietId:String(S.areaDetailId),SubjektTyp:arSubject.value,Verkehrsart:arMode.value,Anforderung:arText.value.trim(),Pflicht:arMandatory.checked,QuelleTyp:arSourceType.value.trim(),Quelle:arSource.value.trim()};if(arChecked.value)f.GeprueftAm=new Date(arChecked.value+'T12:00:00').toISOString();f.Aktiv=true;await api.createItemByName('GebietsAnforderungen',f);rerenderKeepPosition('area-reqs')}catch(e){alert(e.message)}}

async function travelcheck(){head('Reisecheck','Planungshilfe · keine rechtsverbindliche Auskunft');app.innerHTML='<div class="card">Stammdaten werden geladen …</div>';try{const api=await getCloud(),[vs,ps,gs]=await Promise.all([list(api,'Fahrzeuge'),list(api,'Personen'),list(api,'Gebiete')]);app.innerHTML=`<div class="card"><div class="field"><label>Fahrzeug</label><select id="tcVehicle">${vs.map(v=>`<option value="${v.id}">${esc(v.fields.Fahrzeugname||v.fields.Title)}</option>`).join('')}</select></div><div class="field"><label>Person</label><select id="tcPerson">${ps.map(p=>`<option value="${p.id}">${esc(p.fields.Anzeigename||p.fields.Title)} · ${esc(p.fields.Rolle||'')}</option>`).join('')}</select></div><div class="field"><label>Gebiet / Revier</label><select id="tcArea">${gs.map(g=>`<option value="${g.id}">${esc(g.fields.Name||g.fields.Title)}</option>`).join('')}</select></div><button class="primary" onclick="runTravelCheckCloud()">Check erstellen</button></div><div id="tcResult"></div><div class="card"><b>Hinweis</b><p>Diese Prüfung dient als Planungshilfe. Vorschriften können sich ändern. Angaben und Anforderungen sind vor Reiseantritt anhand geeigneter aktueller Quellen zu prüfen.</p></div>`}catch(e){failBox(e)}}
async function runTravelCheckCloud(){const out=document.querySelector('#tcResult');out.innerHTML='<div class="card">Prüfung wird erstellt …</div>';try{const api=await getCloud(),[reqs,quals]=await Promise.all([list(api,'GebietsAnforderungen'),list(api,'Befaehigungen')]),own=reqs.filter(r=>String(r.fields.GebietId)===String(tcArea.value)),pq=quals.filter(q=>String(q.fields.PersonId)===String(tcPerson.value));const rows=own.map(r=>{let result='ZuPruefen',note='Aktuell prüfen und bestätigen.';if(r.fields.SubjektTyp==='Person'&&pq.length){const text=(r.fields.Anforderung||'').toLowerCase(),hit=pq.find(q=>q.fields.Vorhanden!==false&&text.includes(String(q.fields.Art||'').toLowerCase()));if(hit){result='Erfuellt';note='Passender hinterlegter Nachweis gefunden: '+hit.fields.Art}}return {r,result,note}});out.innerHTML=`<div class="card ${rows.some(x=>x.result!=='Erfuellt')?'status-warn':'status-ok'}"><b>${rows.length?'Prüfliste':'Keine Anforderungen hinterlegt'}</b>${rows.map(x=>`<div class="checkresult"><b>${x.result==='Erfuellt'?'✓':'○'} ${esc(x.r.fields.SubjektTyp)} · ${esc(x.r.fields.Verkehrsart)}</b><div>${esc(x.r.fields.Anforderung)}</div><div class="muted">${esc(x.note)}</div></div>`).join('')}${rows.length?'<button onclick="saveTravelCheck()">Check in SharePoint speichern</button>':''}</div>`;S.lastTravelCheck={vehicleId:tcVehicle.value,personId:tcPerson.value,areaId:tcArea.value,rows}}catch(e){out.innerHTML=`<div class="card status-stop">${esc(e.message)}</div>`}}
async function saveTravelCheck(){try{const api=await getCloud(),h=await api.createItemByName('Reisechecks',{NutzungId:'',ErstelltAm:new Date().toISOString(),Status:S.lastTravelCheck.rows.every(x=>x.result==='Erfuellt')?'Vollstaendig':'Unvollstaendig'});for(const x of S.lastTravelCheck.rows)await api.createItemByName('ReisecheckPunkte',{ReisecheckId:String(h.id),GebietsAnforderungId:String(x.r.id),SubjektTyp:x.r.fields.SubjektTyp,SubjektId:x.r.fields.SubjektTyp==='Person'?String(S.lastTravelCheck.personId):x.r.fields.SubjektTyp==='Fahrzeug'?String(S.lastTravelCheck.vehicleId):'',Anforderung:x.r.fields.Anforderung,Ergebnis:x.result,Notiz:x.note});alert('Reisecheck gespeichert.')}catch(e){alert(e.message)}}

function start(){head('Start','Nutzung und Rückblick');app.innerHTML=`<div class="grid"><button class="menu" onclick="go('vehicle')"><b>Neue Nutzung</b></button><button class="menu" onclick="go('history')"><b>Bisherige Nutzungen</b></button><button class="menu"><b>Foto / Film</b></button></div>`}
async function vehicle(){head('Fahrzeug auswählen');app.innerHTML='<div class="card">Fahrzeuge werden geladen …</div>';try{const api=await getCloud(),vs=await list(api,'Fahrzeuge');const active=vs.filter(v=>v.fields.Aktiv!==false);app.innerHTML=`<div class="grid">${active.map(v=>`<button class="menu" onclick='selectCloudVehicle(${JSON.stringify(JSON.stringify({id:v.id,name:v.fields.Fahrzeugname||v.fields.Title,profile:v.fields.Profil||"Motorboot"}))})'><b>${esc(v.fields.Fahrzeugname||v.fields.Title)}</b><span class="muted">${esc(v.fields.Profil||v.fields.Fahrzeugtyp||'')}</span></button>`).join('')}</div>`}catch(e){failBox(e)}}
function selectCloudVehicle(raw){const v=JSON.parse(raw);S.vehicle={id:String(v.id),name:v.name,profile:v.profile==='Wohnmobil'?'motorhome':'motorboat',profileLabel:v.profile};go('usage')}
async function usage(){head('Nutzungsart',S.vehicle.name);app.innerHTML='<div class="card">Nutzungsarten werden geladen …</div>';try{const api=await getCloud(),[maps,types]=await Promise.all([list(api,'FahrzeugNutzungsarten'),list(api,'Nutzungsarten')]);const typeById=Object.fromEntries(types.map(x=>[String(x.id),x]));const rows=maps.filter(x=>String(x.fields.FahrzeugId)===String(S.vehicle.id)&&x.fields.Aktiv!==false).sort((a,b)=>(a.fields.Sortierung||0)-(b.fields.Sortierung||0)).map(m=>typeById[String(m.fields.NutzungsartId)]).filter(Boolean).filter(t=>t.fields.Aktiv!==false);app.innerHTML=rows.length?`<div class="grid">${rows.map(t=>{const n=t.fields.Name||t.fields.Title;const multi=['Törn','Kurztrip','Urlaub'].includes(n);return `<button class="menu" onclick="S.usage={id:'${t.id}',name:'${esc(n)}',multi:${multi}};go('setup')"><b>${esc(n)}</b><span class="muted">${multi?'mehrtägige Nutzung':'eintägige Nutzung'}</span></button>`}).join('')}</div>`:'<div class="card status-warn"><b>Keine Nutzungsart aktiviert.</b><p>Bitte unter Konfiguration → Fahrzeuge die Nutzungsarten dieses Fahrzeugs festlegen.</p></div>'}catch(e){failBox(e)}}
function startMeters(){if(S.vehicle.profile==='motorboat')return `<div class="field"><label>Betriebsstunden Start · Motor 1</label><input id="sm0" type="number" step="0.1"></div><div class="field"><label>Betriebsstunden Start · Motor 2</label><input id="sm1" type="number" step="0.1"></div>`;return `<div class="field"><label>Kilometerstand Start</label><input id="sm0" type="number" step="1"></div>`}
function locSelect(prefix,label,orts,sites){
 const sorted=[...orts].filter(o=>o.fields.Aktiv!==false).sort((a,b)=>((b.fields.Favorit?1000:0)+(b.fields.Verwendungen||0))-((a.fields.Favorit?1000:0)+(a.fields.Verwendungen||0))||String(a.fields.Name||'').localeCompare(String(b.fields.Name||'')));
 return `<div class="location-box"><label>${label}</label><div class="grid compact"><select id="${prefix}Ort" onchange="refreshSiteOptions('${prefix}')"><option value="">– Ort auswählen –</option>${sorted.map(o=>`<option value="${o.id}">${o.fields.Favorit?'★ ':''}${esc(o.fields.Name||o.fields.Title)}</option>`).join('')}</select><select id="${prefix}Standort" data-sites='${esc(JSON.stringify(sites.map(s=>({id:s.id,ort:String(s.fields.OrtId||''),name:s.fields.Name||s.fields.Title,type:s.fields.Standorttyp||'' ,active:s.fields.Aktiv!==false,fav:!!s.fields.Favorit}))))}'><option value="">– konkreter Standort optional –</option></select></div><button type="button" class="small-action" onclick="quickAddPlace('${prefix}')">+ neuen Ort anlegen</button></div>`;
}
function refreshSiteOptions(prefix){const o=document.getElementById(prefix+'Ort'),s=document.getElementById(prefix+'Standort');if(!o||!s)return;let rows=[];try{rows=JSON.parse(s.dataset.sites||'[]')}catch{}const oid=String(o.value||'');s.innerHTML='<option value="">– konkreter Standort optional –</option>'+rows.filter(x=>x.active&&String(x.ort)===oid).sort((a,b)=>(b.fav?1:0)-(a.fav?1:0)||a.name.localeCompare(b.name)).map(x=>`<option value="${x.id}">${x.fav?'★ ':''}${esc(x.name)}${x.type?' · '+esc(x.type):''}</option>`).join('')}
async function quickAddPlace(prefix){const n=prompt('Neuen Ort einmalig anlegen:');if(!n||!n.trim())return;try{const api=await getCloud(),all=await list(api,'Orte'),name=n.trim();let hit=all.find(x=>(x.fields.Name||x.fields.Title||'').trim().toLowerCase()===name.toLowerCase());if(!hit)hit=await api.createItemByName('Orte',{Title:name,Name:name,Verwendungen:0,Aktiv:true});await setup();setTimeout(()=>{const el=document.getElementById(prefix+'Ort');if(el){el.value=String(hit.id);refreshSiteOptions(prefix)}},120)}catch(e){alert(e.message)}}
function locValue(prefix,orts,sites){const oid=document.getElementById(prefix+'Ort')?.value||'',sid=document.getElementById(prefix+'Standort')?.value||'',o=orts.find(x=>String(x.id)===String(oid)),s=sites.find(x=>String(x.id)===String(sid));return {ortId:oid,standortId:sid,text:s?.fields?.Name||o?.fields?.Name||''}}
function addPlannedStop(){const o=document.getElementById('stopOrt'),s=document.getElementById('stopStandort');if(!o||!o.value)return alert('Bitte Ort auswählen.');const on=o.options[o.selectedIndex]?.text.replace(/^★ /,'')||'',sn=s&&s.value?s.options[s.selectedIndex]?.text.replace(/^★ /,''):'';const list=document.getElementById('plannedStops');const d=document.createElement('div');d.className='line planned-stop';d.dataset.ortId=o.value;d.dataset.standortId=s?.value||'';d.innerHTML=`<div><b>${esc(on)}</b>${sn?`<div class="muted">${esc(sn)}</div>`:''}</div><button type="button" onclick="this.parentElement.remove()">Entfernen</button>`;list.appendChild(d)}

async function setup(){let p=P[S.vehicle.profile];head('Startangaben',`${S.vehicle.name} · ${S.usage.name}`);app.innerHTML='<div class="card">Stammdaten werden geladen …</div>';try{
const api=await getCloud(),[persons,funcs,orts,sites]=await Promise.all([list(api,'Personen'),list(api,'PersonFunktionen'),list(api,'Orte'),list(api,'Standorte')]);S.locationData={orts,sites};
const active=persons.filter(x=>x.fields.Aktiv!==false),idsFor=fn=>new Set(funcs.filter(x=>x.fields.Funktion===fn&&x.fields.Aktiv!==false).map(x=>String(x.fields.PersonId))),
primary=p.functions[0],secondary=p.functions[1],primIds=idsFor(primary),secIds=idsFor(secondary),guestIds=idsFor('Gast'),
opts=arr=>arr.map(x=>`<option value="${x.id}">${esc(x.fields.Anzeigename||x.fields.Title)}</option>`).join(''),
prim=active.filter(x=>primIds.has(String(x.id))),sec=active.filter(x=>secIds.has(String(x.id))),guests=active.filter(x=>guestIds.has(String(x.id))),multi=S.usage.multi;
app.innerHTML=`<div class="card">${multi?`<div class="section first">Gesamtplanung ${esc(S.usage.name)}</div><div class="grid compact"><div class="field"><label>Geplanter Start *</label><input id="planFrom" type="date"></div><div class="field"><label>Geplantes Ende *</label><input id="planTo" type="date"></div></div>${locSelect('planStart','Geplanter Startort',orts,sites)}${locSelect('planEnd','Geplanter Endort',orts,sites)}<div class="section">Geplante Zwischenziele</div>${locSelect('stop','Zwischenziel auswählen',orts,sites)}<button type="button" onclick="addPlannedStop()">Zwischenziel hinzufügen</button><div id="plannedStops"></div><hr>`:''}<div class="section first">${multi?'Heutige Tagesetappe':'Nutzung'}</div>${locSelect('dayStart','Startpunkt',orts,sites)}${locSelect('dayGoal',multi?'Heutiges Tagesziel':'Geplantes Ziel (optional)',orts,sites)}<div class="section">Personen</div><div class="field"><label>${primary} · genau eine Person</label><select id="primaryPerson"><option value="">– auswählen –</option>${opts(prim)}</select></div><div class="field"><label>${secondary} · 0 bis X</label><select id="secondaryPeople" multiple size="${Math.min(5,Math.max(2,sec.length))}">${opts(sec)}</select></div><div class="field"><label>Gäste · 0 bis X</label><select id="guestPeople" multiple size="${Math.min(5,Math.max(2,guests.length))}">${opts(guests)}</select></div><div class="section">Tages-Anfangsstand</div>${startMeters()}<button class="primary" onclick="beginCloud()">Nutzung starten</button></div>`;
['planStart','planEnd','stop','dayStart','dayGoal'].forEach(refreshSiteOptions);
}catch(e){failBox(e)}}
function selectedValues(el){return [...el.selectedOptions].map(x=>x.value)}
async function beginCloud(){if(!primaryPerson.value)return alert(`Bitte ${P[S.vehicle.profile].functions[0]} auswählen.`);if(S.usage.multi&&(!planFrom.value||!planTo.value))return alert('Geplanten Start und geplantes Ende eingeben.');try{
const api=await getCloud(),now=new Date().toISOString(),multi=S.usage.multi,orts=S.locationData?.orts||[],sites=S.locationData?.sites||[],
ds=locValue('dayStart',orts,sites),dg=locValue('dayGoal',orts,sites),ps=multi?locValue('planStart',orts,sites):{ortId:'',standortId:'',text:''},pe=multi?locValue('planEnd',orts,sites):{ortId:'',standortId:'',text:''};
const fields={Title:`${S.vehicle.name} · ${S.usage.name}`,FahrzeugId:String(S.vehicle.id),BenutzerId:'current',NutzungsartId:String(S.usage.id),Beginn:now,Status:'Aktiv',Startpunkt:ds.text,GeplantesZiel:dg.text};
if(multi){fields.GeplanterBeginn=new Date(planFrom.value+'T12:00:00').toISOString();fields.GeplantesEndeDatum=new Date(planTo.value+'T12:00:00').toISOString();fields.GeplanterStartort=ps.text;fields.GeplanterEndort=pe.text;fields.GeplanterStartOrtId=ps.ortId;fields.GeplanterStartStandortId=ps.standortId;fields.GeplanterEndOrtId=pe.ortId;fields.GeplanterEndStandortId=pe.standortId}
const u=await api.createItemByName('Nutzungen',fields);
const day=await api.createItemByName('Tagesetappen',{NutzungId:String(u.id),FahrzeugId:String(S.vehicle.id),TagNr:1,Datum:now,Startpunkt:ds.text,Tagesziel:dg.text,Beginn:now,Status:'Aktiv',StartOrtId:ds.ortId,StartStandortId:ds.standortId,ZielOrtId:dg.ortId,ZielStandortId:dg.standortId});
if(multi){const stops=[...document.querySelectorAll('.planned-stop')];for(let i=0;i<stops.length;i++){const d=stops[i],o=orts.find(x=>String(x.id)===String(d.dataset.ortId)),s=sites.find(x=>String(x.id)===String(d.dataset.standortId));await api.createItemByName('NutzungsZwischenziele',{NutzungId:String(u.id),Sortierung:i+1,Ort:s?.fields?.Name||o?.fields?.Name||'',OrtId:d.dataset.ortId||'',StandortId:d.dataset.standortId||''})}}
const primary=P[S.vehicle.profile].functions[0];await api.createItemByName('NutzungsPersonen',{NutzungId:String(u.id),TagesetappeId:String(day.id),PersonId:primaryPerson.value,Funktion:primary});
for(const id of selectedValues(secondaryPeople))await api.createItemByName('NutzungsPersonen',{NutzungId:String(u.id),TagesetappeId:String(day.id),PersonId:id,Funktion:P[S.vehicle.profile].functions[1]});
for(const id of selectedValues(guestPeople))await api.createItemByName('NutzungsPersonen',{NutzungId:String(u.id),TagesetappeId:String(day.id),PersonId:id,Funktion:'Gast'});
for(const v of [ds,dg,ps,pe])if(v.ortId){const o=orts.find(x=>String(x.id)===String(v.ortId));try{await api.updateItemByName('Orte',v.ortId,{Verwendungen:Number(o?.fields?.Verwendungen||0)+1,ZuletztVerwendet:now})}catch{}}
S.usage.cloudId=String(u.id);S.day={id:String(day.id),start:ds.text,goal:dg.text,startMeters:[...document.querySelectorAll('[id^=sm]')].map(x=>x.value)};localStorage.setItem('fp-current',JSON.stringify({vehicle:S.vehicle,usage:S.usage,day:S.day,startedAt:now}));go('cockpit')
}catch(e){alert('Nutzung konnte nicht gestartet werden: '+e.message)}}
function cockpit(){let p=P[S.vehicle.profile];head('Cockpit',`${S.vehicle.name} · ${S.usage.name}`);app.innerHTML=`<div class="cockpit">${p.actions.map((a,i)=>`<button onclick="${i===2?"go('event')":i===3?"go('stay')":"void(0)"}">${a}</button>`).join('')}</div><div class="secondary"><button>Tanken / Versorgung</button><button>Foto</button><button>Film</button><button>Füllstände</button><button>Besatzung ändern</button><button onclick="go('dayend')">Tagesabschluss</button></div>`}
function event(){let p=P[S.vehicle.profile];head('Ereignis',S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Ereignisart</label><select>${p.events.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Bemerkung</label><textarea></textarea></div><button class="primary" onclick="back()">Speichern</button></div>`}
function stay(){let p=P[S.vehicle.profile];head(p.actions[3],S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Aufenthaltsart</label><select>${p.stays.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Ort</label><input></div><button class="primary" onclick="back()">Speichern</button></div>`}
function endMeters(){if(S.vehicle.profile==='motorboat')return S.vehicle.engines.map((e,i)=>`<div class="field"><label>Betriebsstunden Ende · ${e}</label><input id="em${i}" type="number" step="0.1"></div>`).join('');return `<div class="field"><label>Kilometerstand Ende</label><input id="em0" type="number" step="1"></div>`}
function dayend(){head('Tagesabschluss',S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Tatsächlicher Tagesziel-/Aufenthaltsort</label><input id="actual"></div>${endMeters()}<div class="field"><label>Tagesnotiz</label><textarea></textarea></div><button class="primary" onclick="finish()">Tag abschließen</button></div>`}
function finish(){let rec=JSON.parse(localStorage.getItem('fp-current')||'{}');rec.day.actualEnd=actual.value;rec.day.endMeters=[...document.querySelectorAll('[id^=em]')].map(x=>x.value);rec.day.endedAt=new Date().toISOString();let hist=JSON.parse(localStorage.getItem('fp-history')||'[]');hist.push(rec);localStorage.setItem('fp-history',JSON.stringify(hist));localStorage.removeItem('fp-current');S.stack=[];S.view='start';render()}
function usageHistory(){head('Bisherige Nutzungen');let h=JSON.parse(localStorage.getItem('fp-history')||'[]');app.innerHTML=h.length?h.reverse().map(x=>`<div class="card"><b>${esc(x.vehicle.name)} · ${esc(x.usage.name)}</b><div class="muted">${esc(x.day.start||'')} → ${esc(x.day.actualEnd||'')}</div></div>`).join(''):'<div class="card">Noch keine abgeschlossenen Tage.</div>'}

async function m365setup(){head('Microsoft 365 Setup','Schema 0.8.0 · additiv');let tok=window.FPAuth.token();app.innerHTML=`<div class="card"><b>Microsoft-Anmeldung</b><p class="muted">Client-ID ist öffentlich und fest hinterlegt. Es gibt kein Client-Secret im Browser.</p><div id="authState">${tok?'✓ Microsoft-Token vorhanden':'Noch nicht mit Microsoft verbunden'}</div>${tok?'<button onclick="FPAuth.logout();render()">Microsoft-Verbindung trennen</button>':'<button class="primary" onclick="sessionStorage.setItem(\'fp_after_auth\',\'m365setup\');FPAuth.login()">Mit Microsoft 365 anmelden</button>'}</div><div class="card"><div class="field"><label>SharePoint-Site-URL</label><input id="spSite" placeholder="https://…sharepoint.com/sites/Fahrzeugplattform" value="${esc(localStorage.getItem('fp_sp_site')||'')}"></div><button class="primary" ${tok?'':'disabled'} onclick="runM365Provision()">Phase-1-Struktur prüfen / anlegen</button><p class="muted">Additiv und wiederholbar: vorhandene Listen/Felder bleiben bestehen, fehlende werden ergänzt.</p></div><div id="m365Result"></div>`}
async function runM365Provision(){const url=document.querySelector('#spSite').value.trim();if(!url){alert('Bitte die vollständige SharePoint-Site-URL eintragen.');return}localStorage.setItem('fp_sp_site',url);const out=document.querySelector('#m365Result');out.innerHTML='<div class="card">Schema wird geladen …</div>';try{const schema=await(await fetch('phase1-sharepoint-schema.json',{cache:'no-store'})).json(),setup=new FPGraphSetup(FPAuth.token(),url,schema),site=await setup.resolveSite();let lines=[];out.innerHTML=`<div class="card"><b>Verbunden:</b> ${esc(site.displayName)}<div id="provLog" class="muted">Prüfung startet …</div></div>`;const log=document.querySelector('#provLog'),res=await setup.provision(e=>{if(e.status==='created')lines.push(`${e.kind==='list'?'Liste':'Feld'} angelegt: ${e.kind==='field'?e.list+' · ':''}${e.name}`);log.innerHTML=`Fortschritt: ${esc(e.kind==='field'?e.list+' · '+e.name:e.name)}<br>${lines.slice(-8).map(esc).join('<br>')}`});out.innerHTML=`<div class="card status-warn"><b>Setup abgeschlossen</b><p>${res.totalLists} Listen geprüft · ${res.listsCreated} neu angelegt · ${res.fieldsCreated} Felder neu angelegt.</p></div>`}catch(e){out.innerHTML=`<div class="card status-stop"><b>Setup nicht abgeschlossen</b><p>${esc(e.message)}</p></div>`}}
function workshop(){head('Werkstatt');app.innerHTML=`<div class="card"><b>Werkstatt</b><p class="muted">Wartung, Reparaturen, Umbauten, Störungen, Prüfungen und technische Dokumente. Grundmaske vorbereitet.</p></div>`}
function lending(){head('Verleihmodus');app.innerHTML=`<div class="card"><b>Verleihmodus</b><p class="muted">Personenrolle „Leiher“ und fahrzeugbezogene Rechte werden hier verwaltet.</p></div>`}
function settings(){head('Einstellungen');app.innerHTML=`<div class="grid"><button class="menu" onclick="go('m365setup')"><b>Microsoft 365 Setup</b><span class="muted">Microsoft anmelden · SharePoint verbinden</span></button><button class="menu"><b>Persönliche Einstellungen</b><span class="muted">Einheiten und spätere App-Optionen</span></button></div>`}
function placeholder(){head('Bereich');app.innerHTML='<div class="card">Grundmaske vorbereitet.</div>'}
async function bootstrap(){try{const hadCode=new URL(location.href).searchParams.has('code');if(hadCode){await FPAuth.handleRedirect();const target=sessionStorage.getItem('fp_after_auth')||'m365setup';sessionStorage.removeItem('fp_after_auth');S.stack=[];S.view=target}}catch(e){bar.hidden=true;app.innerHTML=`<div class="login"><div class="card status-stop"><b>Microsoft-Anmeldung nicht abgeschlossen</b><p>${esc(e.message)}</p><button class="primary" onclick="location.href=FPAuth.cfg.redirectUri">Zur Fahrzeugplattform</button></div></div>`;return}render()}
bootstrap();
