const VERSION='0.2.0-dev';
const P={
  motorboat:{label:'Motorboot',functions:['Skipper','Crew','Gast'],usage:[['Ausfahrt',0],['Törn',1],['Wasserski',0]],events:['Schleuse','Bewegliche Brücke','Hebewerk','Peilung / Landmarke','Besondere Begegnung','Wetter','Wetteränderung','Technische Beobachtung','Freie Notiz'],stays:['Angelegt','Vor Anker','Mooring'],actions:['Kontrolle','Ablegen','Ereignis','Anlegen / Ankern']},
  motorhome:{label:'Wohnmobil',functions:['Fahrer','Beifahrer','Gast'],usage:[['Tagesausflug',0],['Kurztrip',1],['Urlaub',1]],events:['Fähre','Besondere Begegnung','Wetter','Wetteränderung','Technische Beobachtung','Freie Notiz'],stays:['Stellplatz','Campingplatz','Freier Stellplatz'],actions:['Kontrolle','Abfahrt','Ereignis','Ankunft / Aufenthalt']}
};
const V=[
  {id:'karoshi',name:'Karõshi',profile:'motorboat',engines:['Motor 1 / BB','Motor 2 / STB']},
  {id:'womo',name:'Wohnmobil',profile:'motorhome'}
];
const seedPersons=[
  {id:'p1',name:'Ralph',role:'Admin',functions:['Skipper','Fahrer','Crew','Beifahrer'],qualifications:[{type:'SBF Binnen',present:true},{type:'UBI',present:true},{type:'SRC',present:false}]},
  {id:'p2',name:'Beispiel Leiher',role:'Leiher',functions:['Fahrer'],qualifications:[{type:'Führerschein B',present:true}]},
  {id:'p3',name:'Beispiel Gast',role:'Gast',functions:['Gast'],qualifications:[]}
];
const seedAreas=[
  {id:'g1',name:'Deutschland',type:'Land',parent:null},
  {id:'g2',name:'Binnengewässer',type:'Revier',parent:'g1'},
  {id:'g3',name:'Seestraßen',type:'Revier',parent:'g1'},
  {id:'g4',name:'Albanien',type:'Land',parent:null}
];
const seedRequirements=[
  {id:'r1',areaId:'g3',subject:'Skipper',requirement:'Befähigung für das geplante Seerevier prüfen',source:'Nutzerrecherche',checkedAt:'',mandatory:true},
  {id:'r2',areaId:'g3',subject:'Funk',requirement:'Bei vorhandener/benutzter Seefunkanlage erforderliches Funkzeugnis prüfen',source:'Nutzerrecherche',checkedAt:'',mandatory:true},
  {id:'r3',areaId:'g4',subject:'Person',requirement:'Erforderliche Reisedokumente prüfen',source:'Nutzerrecherche',checkedAt:'',mandatory:true},
  {id:'r4',areaId:'g4',subject:'Fahrzeug',requirement:'Fahrzeug- und Versicherungsnachweise prüfen',source:'Nutzerrecherche',checkedAt:'',mandatory:true},
  {id:'r5',areaId:'g4',subject:'Tier',requirement:'Einreiseanforderungen für Hund/Katze prüfen',source:'Nutzerrecherche',checkedAt:'',mandatory:true}
];
function init(){if(!localStorage.getItem('fp-persons'))localStorage.setItem('fp-persons',JSON.stringify(seedPersons));if(!localStorage.getItem('fp-areas'))localStorage.setItem('fp-areas',JSON.stringify(seedAreas));if(!localStorage.getItem('fp-requirements'))localStorage.setItem('fp-requirements',JSON.stringify(seedRequirements));}
init();
let S={view:'login',stack:[],vehicle:null,usage:null,day:null};
const app=document.querySelector('#app'),bar=document.querySelector('#bar'),title=document.querySelector('#title'),sub=document.querySelector('#sub');
function head(t,s=''){bar.hidden=false;title.textContent=t;sub.textContent=s}
function go(v){S.stack.push(S.view);S.view=v;render()}
function back(){if(S.stack.length){S.view=S.stack.pop();render()}}
function show(v){go(v)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){({login,main,start,vehicle,usage,setup,cockpit,event,stay,dayend,history,configuration,persons,areas,travelcheck,workshop,lending,settings}[S.view]||placeholder)()}
function login(){bar.hidden=true;app.innerHTML=`<div class="login"><div class="card"><div class="brand">Fahrzeugplattform</div><p class="muted">Version ${VERSION}</p><div class="field"><label>Nutzer</label><input value="Admin"></div><div class="field"><label>Passwort</label><input type="password" value="admin"></div><button class="primary" onclick="S.stack=[];S.view='main';render()">Anmelden</button></div></div>`}
function main(){S.stack=[];head('Fahrzeugplattform','Admin');app.innerHTML=`<div class="grid">${[['Start','start'],['Konfiguration','configuration'],['Werkstatt','workshop'],['Verleihmodus','lending']].map(x=>`<button class="menu" onclick="go('${x[1]}')"><b>${x[0]}</b></button>`).join('')}</div>`}
function configuration(){head('Konfiguration','Stammdaten und Grundlagen');app.innerHTML=`<div class="grid"><button class="menu"><b>Fahrzeuge</b><span class="muted">Fahrzeug, Komponenten, Einheiten</span></button><button class="menu" onclick="go('persons')"><b>Personen</b><span class="muted">Rollen, Funktionen, Nachweise</span></button><button class="menu" onclick="go('areas')"><b>Gebiete / Reviere</b><span class="muted">Länder, Reviere, Anforderungen</span></button><button class="menu" onclick="go('travelcheck')"><b>Reisecheck</b><span class="muted">Soll/Ist vor einer Reise</span></button></div>`}
function persons(){head('Personen','Rolle · Funktionen · Befähigungen');const ps=JSON.parse(localStorage.getItem('fp-persons')||'[]');app.innerHTML=ps.map(p=>`<div class="card"><b>${esc(p.name)}</b><div class="kv"><span>Rolle</span><strong>${esc(p.role)}</strong><span>Funktionen</span><div class="tagrow">${p.functions.map(f=>`<span class="tag">${esc(f)}</span>`).join('')}</div><span>Nachweise</span><div>${p.qualifications.length?p.qualifications.map(q=>`<div>${q.present?'✓':'○'} ${esc(q.type)}</div>`).join(''):'Keine erforderlich/hinterlegt'}</div></div></div>`).join('')+`<div class="card"><p class="muted">Prinzip: Rolle steuert App-Rechte. Funktionen können mehrfach möglich sein und werden je Nutzung/Tag tatsächlich zugeordnet. Nachweise können als vorhanden Ja/Nein oder später mit Nummer, Gültigkeit und Dokument erfasst werden.</p></div>`}
function areas(){head('Gebiete / Reviere','Anforderungen werden vom Nutzer gepflegt');const gs=JSON.parse(localStorage.getItem('fp-areas')||'[]'),rs=JSON.parse(localStorage.getItem('fp-requirements')||'[]');app.innerHTML=gs.map(g=>{const own=rs.filter(r=>r.areaId===g.id);return `<div class="card"><b>${esc(g.name)}</b> <span class="tag">${esc(g.type)}</span>${own.length?`<div class="section">Hinterlegte Prüfpunkte</div>${own.map(r=>`<div>• <b>${esc(r.subject)}:</b> ${esc(r.requirement)}</div>`).join('')}`:'<p class="muted">Noch keine Anforderungen hinterlegt.</p>'}</div>`}).join('')+`<div class="card"><p class="muted">Die App behauptet nicht, alle Vorschriften zu kennen. Nutzer recherchieren Anforderungen und hinterlegen sie mit Quelle/Stand. Später kann die Community anonymisierte Vorschläge liefern.</p></div>`}
function travelcheck(){head('Reisecheck','Planungshilfe · keine rechtsverbindliche Auskunft');app.innerHTML=`<div class="card"><div class="field"><label>Fahrzeug</label><select id="tcVehicle">${V.map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('')}</select></div><div class="field"><label>Person</label><select id="tcPerson">${JSON.parse(localStorage.getItem('fp-persons')||'[]').map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.role)}</option>`).join('')}</select></div><div class="field"><label>Gebiet / Revier</label><select id="tcArea">${JSON.parse(localStorage.getItem('fp-areas')||'[]').map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select></div><button class="primary" onclick="runTravelCheck()">Check erstellen</button></div><div id="tcResult"></div><div class="card"><b>Hinweis</b><p>Diese Prüfung dient als Planungshilfe. Vorschriften können sich ändern. Angaben und Anforderungen sind vor Reiseantritt anhand geeigneter aktueller Quellen zu prüfen.</p></div>`}
function runTravelCheck(){const person=JSON.parse(localStorage.getItem('fp-persons')||'[]').find(p=>p.id===tcPerson.value),area=JSON.parse(localStorage.getItem('fp-areas')||'[]').find(g=>g.id===tcArea.value),reqs=JSON.parse(localStorage.getItem('fp-requirements')||'[]').filter(r=>r.areaId===tcArea.value);let warnings=[];if(area&&area.name==='Seestraßen'&&person){const src=person.qualifications.find(q=>q.type==='SRC');if(!src||!src.present)warnings.push('SRC ist für diese Person nicht als vorhanden hinterlegt. Anforderungen für Funk/Seerevier prüfen.');}const reqHtml=reqs.length?reqs.map(r=>`<div>○ <b>${esc(r.subject)}</b> – ${esc(r.requirement)}</div>`).join(''):'<div>Für dieses Gebiet sind noch keine Anforderungen hinterlegt. Nutzerrecherche erforderlich.</div>';document.querySelector('#tcResult').innerHTML=`<div class="card ${warnings.length?'status-stop':'status-warn'}"><b>${warnings.length?'Konflikt/offener Punkt erkannt':'Prüfliste'}</b><div style="margin-top:10px">${warnings.map(w=>`<div>⚠ ${esc(w)}</div>`).join('')}${reqHtml}</div></div>`}
function start(){head('Start','Nutzung und Rückblick');app.innerHTML=`<div class="grid"><button class="menu" onclick="go('vehicle')"><b>Neue Nutzung</b></button><button class="menu" onclick="go('history')"><b>Bisherige Nutzungen</b></button><button class="menu"><b>Foto / Film</b></button></div>`}
function vehicle(){head('Fahrzeug auswählen');app.innerHTML=`<div class="grid">${V.map((v,i)=>`<button class="menu" onclick="S.vehicle=V[${i}];go('usage')"><b>${v.name}</b><span class="muted">${P[v.profile].label}</span></button>`).join('')}</div>`}
function usage(){let p=P[S.vehicle.profile];head('Nutzungsart',S.vehicle.name);app.innerHTML=`<div class="grid">${p.usage.map((u,i)=>`<button class="menu" onclick="S.usage={name:'${u[0]}',multi:${u[1]}};go('setup')"><b>${u[0]}</b><span class="muted">${u[1]?'mehrtägig möglich':'eintägig'}</span></button>`).join('')}</div>`}
function startMeters(){if(S.vehicle.profile==='motorboat')return S.vehicle.engines.map((e,i)=>`<div class="field"><label>Betriebsstunden Start · ${e}</label><input id="sm${i}" type="number" step="0.1"></div>`).join('');return `<div class="field"><label>Kilometerstand Start</label><input id="sm0" type="number" step="1"></div>`}
function setup(){let p=P[S.vehicle.profile];head('Startangaben',`${S.vehicle.name} · ${S.usage.name}`);app.innerHTML=`<div class="card"><div class="field"><label>Startpunkt</label><input id="sp"></div><div class="field"><label>${S.usage.multi?'Tagesziel':'Geplantes Ziel (optional)'}</label><input id="goal"></div>${S.usage.multi?'<div class="field"><label>Zwischenziele (optional)</label><input></div>':''}<div class="grid"><div class="field"><label>${p.functions[0]}</label><input></div><div class="field"><label>${p.functions[1]}</label><input></div></div><div class="field"><label>${p.functions[2]}</label><input></div><div class="section">Tages-Anfangsstand</div>${startMeters()}<button class="primary" onclick="begin()">Nutzung starten</button></div>`}
function begin(){S.day={start:sp.value,goal:goal.value,startMeters:[...document.querySelectorAll('[id^=sm]')].map(x=>x.value)};localStorage.setItem('fp-current',JSON.stringify({vehicle:S.vehicle,usage:S.usage,day:S.day,startedAt:new Date().toISOString()}));go('cockpit')}
function cockpit(){let p=P[S.vehicle.profile];head('Cockpit',`${S.vehicle.name} · ${S.usage.name}`);app.innerHTML=`<div class="cockpit">${p.actions.map((a,i)=>`<button onclick="${i===2?"go('event')":i===3?"go('stay')":"void(0)"}">${a}</button>`).join('')}</div><div class="secondary"><button>Tanken / Versorgung</button><button>Foto</button><button>Film</button><button>Füllstände</button><button>Besatzung ändern</button><button onclick="go('dayend')">Tagesabschluss</button></div>`}
function event(){let p=P[S.vehicle.profile];head('Ereignis',S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Ereignisart</label><select>${p.events.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Bemerkung</label><textarea></textarea></div><button class="primary" onclick="back()">Speichern</button></div>`}
function stay(){let p=P[S.vehicle.profile];head(p.actions[3],S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Aufenthaltsart</label><select>${p.stays.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Ort</label><input></div><button class="primary" onclick="back()">Speichern</button></div>`}
function endMeters(){if(S.vehicle.profile==='motorboat')return S.vehicle.engines.map((e,i)=>`<div class="field"><label>Betriebsstunden Ende · ${e}</label><input id="em${i}" type="number" step="0.1"></div>`).join('');return `<div class="field"><label>Kilometerstand Ende</label><input id="em0" type="number" step="1"></div>`}
function dayend(){head('Tagesabschluss',S.vehicle.name);app.innerHTML=`<div class="card"><div class="field"><label>Tatsächlicher Tagesziel-/Aufenthaltsort</label><input id="actual"></div>${endMeters()}<div class="field"><label>Tagesnotiz</label><textarea></textarea></div><button class="primary" onclick="finish()">Tag abschließen</button></div>`}
function finish(){let rec=JSON.parse(localStorage.getItem('fp-current')||'{}');rec.day.actualEnd=actual.value;rec.day.endMeters=[...document.querySelectorAll('[id^=em]')].map(x=>x.value);rec.day.endedAt=new Date().toISOString();let hist=JSON.parse(localStorage.getItem('fp-history')||'[]');hist.push(rec);localStorage.setItem('fp-history',JSON.stringify(hist));localStorage.removeItem('fp-current');S.stack=[];S.view='start';render()}
function history(){head('Bisherige Nutzungen');let h=JSON.parse(localStorage.getItem('fp-history')||'[]');app.innerHTML=h.length?h.reverse().map(x=>`<div class="card"><b>${esc(x.vehicle.name)} · ${esc(x.usage.name)}</b><div class="muted">${esc(x.day.start||'')} → ${esc(x.day.actualEnd||'')}</div></div>`).join(''):'<div class="card">Noch keine abgeschlossenen Tage.</div>'}
function workshop(){head('Werkstatt');app.innerHTML=`<div class="card"><b>Werkstatt</b><p class="muted">Wartung, Reparaturen, Umbauten, Störungen, Prüfungen und technische Dokumente. Grundmaske vorbereitet.</p></div>`}
function lending(){head('Verleihmodus');app.innerHTML=`<div class="card"><b>Verleihmodus</b><p class="muted">Personenrolle „Leiher“ und fahrzeugbezogene Rechte werden hier verwaltet. Die fachliche Eignung wird zusätzlich über Befähigungen/Nachweise geprüft.</p></div>`}
function settings(){head('Einstellungen');app.innerHTML=`<div class="card"><b>Einstellungen</b><p class="muted">Persönliche Einstellungen, Einheiten und spätere App-Optionen.</p></div>`}
function placeholder(){head('Bereich');app.innerHTML='<div class="card">Grundmaske vorbereitet.</div>'}
render();
