-- Fahrzeugplattform Phase 1 – Kernmodell 0.2.0
-- Fachliches Zielmodell; DB-Dialekt wird später festgelegt.

CREATE TABLE DataRooms(Id TEXT PRIMARY KEY, Name TEXT NOT NULL);
CREATE TABLE Users(Id TEXT PRIMARY KEY, DataRoomId TEXT NOT NULL, LoginName TEXT NOT NULL, Status TEXT NOT NULL);
CREATE TABLE Persons(Id TEXT PRIMARY KEY, DataRoomId TEXT NOT NULL, DisplayName TEXT NOT NULL, Role TEXT NOT NULL, Active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE PersonFunctions(Id TEXT PRIMARY KEY, PersonId TEXT NOT NULL, FunctionType TEXT NOT NULL);
CREATE TABLE Qualifications(Id TEXT PRIMARY KEY, PersonId TEXT NOT NULL, QualificationType TEXT NOT NULL, Present INTEGER NOT NULL DEFAULT 0, Number TEXT, ValidFrom TEXT, ValidUntil TEXT, Issuer TEXT, DocumentId TEXT, CheckedAt TEXT);
CREATE TABLE Animals(Id TEXT PRIMARY KEY, DataRoomId TEXT NOT NULL, Name TEXT NOT NULL, Species TEXT NOT NULL, ChipNumber TEXT, PassportNumber TEXT);
CREATE TABLE AnimalDocuments(Id TEXT PRIMARY KEY, AnimalId TEXT NOT NULL, DocumentType TEXT NOT NULL, Present INTEGER NOT NULL DEFAULT 0, ValidUntil TEXT, DocumentId TEXT);

CREATE TABLE Vehicles(Id TEXT PRIMARY KEY,DataRoomId TEXT NOT NULL,Name TEXT NOT NULL,Profile TEXT NOT NULL);
CREATE TABLE VehicleAttributes(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,AttributeType TEXT NOT NULL,ValueText TEXT,ValueNumber REAL,Unit TEXT);
CREATE TABLE Components(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,ParentComponentId TEXT,Type TEXT NOT NULL,Name TEXT NOT NULL);
CREATE TABLE ComponentAttributes(Id TEXT PRIMARY KEY,ComponentId TEXT NOT NULL,AttributeType TEXT NOT NULL,ValueText TEXT,ValueNumber REAL,Unit TEXT);

CREATE TABLE Areas(Id TEXT PRIMARY KEY,Name TEXT NOT NULL,AreaType TEXT NOT NULL,ParentAreaId TEXT);
CREATE TABLE AreaRequirements(Id TEXT PRIMARY KEY,AreaId TEXT NOT NULL,SubjectType TEXT NOT NULL,TravelMode TEXT,RequirementText TEXT NOT NULL,Mandatory INTEGER NOT NULL DEFAULT 1,SourceType TEXT,SourceReference TEXT,CheckedAt TEXT,ValidFrom TEXT,ValidUntil TEXT);

CREATE TABLE Usages(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UserId TEXT NOT NULL,UsageType TEXT NOT NULL,StartedAt TEXT NOT NULL,EndedAt TEXT,Status TEXT NOT NULL,StartPoint TEXT,PlannedGoal TEXT);
CREATE TABLE UsageAreas(Id TEXT PRIMARY KEY,UsageId TEXT NOT NULL,AreaId TEXT NOT NULL,TravelMode TEXT);
CREATE TABLE DailyStages(Id TEXT PRIMARY KEY,UsageId TEXT NOT NULL,VehicleId TEXT NOT NULL,DayNo INTEGER NOT NULL,Date TEXT NOT NULL,StartPoint TEXT,PlannedGoal TEXT,ActualEndPoint TEXT,StartedAt TEXT,EndedAt TEXT,Status TEXT NOT NULL);
CREATE TABLE UsagePersons(Id TEXT PRIMARY KEY,UsageId TEXT NOT NULL,DailyStageId TEXT,PersonId TEXT NOT NULL,ActualFunction TEXT NOT NULL);
CREATE TABLE UsageAnimals(Id TEXT PRIMARY KEY,UsageId TEXT NOT NULL,AnimalId TEXT NOT NULL);
CREATE TABLE TravelChecks(Id TEXT PRIMARY KEY,UsageId TEXT NOT NULL,CreatedAt TEXT NOT NULL,Status TEXT NOT NULL,DisclaimerAcceptedAt TEXT);
CREATE TABLE TravelCheckItems(Id TEXT PRIMARY KEY,TravelCheckId TEXT NOT NULL,AreaRequirementId TEXT,SubjectType TEXT NOT NULL,SubjectId TEXT,RequirementText TEXT NOT NULL,Result TEXT NOT NULL,UserConfirmedAt TEXT,Note TEXT);

CREATE TABLE Events(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,DailyStageId TEXT,UserId TEXT NOT NULL,Type TEXT NOT NULL,OccurredAt TEXT NOT NULL,Note TEXT);
CREATE TABLE Stays(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT NOT NULL,DailyStageId TEXT,Type TEXT NOT NULL,PlaceText TEXT,StartedAt TEXT NOT NULL,EndedAt TEXT);
CREATE TABLE Measurements(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,DailyStageId TEXT,ComponentId TEXT,Quantity TEXT NOT NULL,Value REAL,Unit TEXT,Phase TEXT,MeasuredAt TEXT NOT NULL,Quality TEXT);
CREATE TABLE SupplyTransactions(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,ComponentId TEXT,SupplyType TEXT NOT NULL,Quantity REAL,Unit TEXT,CostAmount REAL,Currency TEXT,OccurredAt TEXT NOT NULL);
CREATE TABLE VehicleCheckpoints(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,Name TEXT NOT NULL,IntervalRuleJson TEXT NOT NULL);
CREATE TABLE Checks(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,DailyStageId TEXT,CheckpointId TEXT,UserId TEXT,CompletedAt TEXT);
CREATE TABLE Issues(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,Category TEXT,Description TEXT,ReportedAt TEXT,Status TEXT);
CREATE TABLE Works(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,ComponentId TEXT,IssueId TEXT,WorkType TEXT,Description TEXT,CompletedAt TEXT,CostAmount REAL,Currency TEXT);
CREATE TABLE Expenses(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,RelatedType TEXT,RelatedId TEXT,ExpenseType TEXT,Amount REAL,Currency TEXT,OccurredAt TEXT);
CREATE TABLE Media(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,UsageId TEXT,DailyStageId TEXT,RelatedType TEXT,RelatedId TEXT,MediaType TEXT,FileRef TEXT,CapturedAt TEXT,AddedAt TEXT);
CREATE TABLE Documents(Id TEXT PRIMARY KEY,DataRoomId TEXT NOT NULL,DocumentType TEXT NOT NULL,Title TEXT NOT NULL,MediaId TEXT,ValidUntil TEXT);
CREATE TABLE VehicleLoans(Id TEXT PRIMARY KEY,VehicleId TEXT NOT NULL,BorrowerPersonId TEXT NOT NULL,StartsAt TEXT NOT NULL,EndsAt TEXT,RightsJson TEXT,Status TEXT);
