/* Fahrzeugplattform M365 Setup 0.4.1 via Microsoft Graph v1.0 */
window.FPGraphSetup = class {
  constructor(token, siteUrl, schema){ this.token=token; this.siteUrl=siteUrl.replace(/\/$/,''); this.schema=schema; this.base='https://graph.microsoft.com/v1.0'; }
  async req(path,opt={}){ const r=await fetch(this.base+path,{...opt,headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json',...(opt.headers||{})}}); const t=await r.text(); let j=null; try{j=t?JSON.parse(t):null}catch{} if(!r.ok) throw new Error(`${r.status} ${r.statusText}${j?.error?.message?': '+j.error.message:t?': '+t:''}`); return j; }
  async resolveSite(){ const u=new URL(this.siteUrl); const p=u.pathname.replace(/^\//,''); const s=await this.req(`/sites/${u.hostname}:/${p}?$select=id,displayName,webUrl`); this.site=s; return s; }
  async lists(){ const r=await this.req(`/sites/${encodeURIComponent(this.site.id)}/lists?$select=id,displayName,name`); return r.value||[]; }
  async columns(listId){ const r=await this.req(`/sites/${encodeURIComponent(this.site.id)}/lists/${encodeURIComponent(listId)}/columns?$select=id,name,displayName`); return r.value||[]; }
  column(f){ const c={name:f.internalName,displayName:f.displayName,required:!!f.required}; switch(f.type){case 'Boolean':c.boolean={};break;case 'Number':c.number={};break;case 'Currency':c.currency={locale:'de-DE'};break;case 'DateTime':c.dateTime={format:'dateTime'};break;case 'Choice':c.choice={allowTextEntry:false,choices:f.choices||[],displayAs:'dropDownMenu'};break;case 'Note':c.text={allowMultipleLines:true};break;default:c.text={allowMultipleLines:false};} return c; }
  async ensureList(def,cache){ let l=cache.find(x=>x.displayName===def.displayName||x.name===def.internalName); if(l) return {...l,status:'exists'}; l=await this.req(`/sites/${encodeURIComponent(this.site.id)}/lists`,{method:'POST',body:JSON.stringify({displayName:def.displayName,list:{template:'genericList'}})}); cache.push(l); return {...l,status:'created'}; }
  async ensureField(list,field,colCache){ let c=colCache.find(x=>x.name===field.internalName||x.displayName===field.displayName); if(c) return 'exists'; c=await this.req(`/sites/${encodeURIComponent(this.site.id)}/lists/${encodeURIComponent(list.id)}/columns`,{method:'POST',body:JSON.stringify(this.column(field))}); colCache.push(c); return 'created'; }
  async provision(progress=()=>{}){ if(!this.site) await this.resolveSite(); const cache=await this.lists(); let lc=0,fc=0; for(const def of this.schema.lists){ const l=await this.ensureList(def,cache); if(l.status==='created')lc++; progress({kind:'list',name:def.displayName,status:l.status}); const cols=await this.columns(l.id); for(const f of def.fields){ const st=await this.ensureField(l,f,cols); if(st==='created')fc++; progress({kind:'field',list:def.displayName,name:f.internalName,status:st}); } } return {listsCreated:lc,fieldsCreated:fc,totalLists:this.schema.lists.length}; }
};
