/* MOBIMORY / Fahrzeugplattform 1.0.6-dev
   Reisecheck mit echter Online-Recherche über einen separaten Research Service.
   Die PWA sendet KEINE Namen, Kennzeichen, FIN/VIN, HIN/CIN, Dokumentnummern,
   E-Mail-Adressen oder Telefonnummern an den Rechercheprovider. Personen/Tiere
   werden nur als P1/P2 bzw. A1/A2 mit relevanten Nachweisarten und Gültigkeiten
   übertragen.

   Ablauf:
   Reise definieren -> aktuelle Web-Recherche -> strukturierte Regeln + offizielle
   Quellen -> Abgleich mit gespeicherten Daten -> Ergebnis speichern.
*/

const FP106_VERSION='1.0.6-dev';
const FP106={data:null,last:null,subjectMap:{}};
const FP106_URL_KEY='mobimory_research_url';
const FP106_TOKEN_KEY='mobimory_research_token';

function fp106Date(v){if(!v)return '–';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}
function fp106DateTime(v){if(!v)return '–';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):`${d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} · ${fp106Date(d)}`}
function fp106Iso(v,end=false){if(!v)return null;const d=new Date(v+(end?'T23:59:59':'T00:00:00'));return Number.isNaN(d.getTime())?null:d.toISOString()}
function fp106Selected(attr){return [...document.querySelectorAll(`[data-${attr}]:checked`)].map(x=>String(x.getAttribute(`data-${attr}`)))}
function fp106StatusClass(v){return v==='Fehlt'?'status-stop':v==='Prüfen'?'status-warn':v==='Erfüllt'?'status-ok':''}
function fp106OldResult(v){return v==='Erfüllt'?'Erfuellt':v==='Fehlt'?'NichtErfuellt':v==='Prüfen'?'ZuPruefen':'Offen'}
function fp106NewResult(v){return v==='Erfuellt'?'Erfüllt':v==='NichtErfuellt'?'Fehlt':v==='ZuPruefen'?'Prüfen':'Nicht relevant'}
function fp106CatOrder(v){return ({Pflicht:0,Wichtig:1,Empfohlen:2,Hinweis:3}[v]??9)}
function fp106StatusOrder(v){return ({Fehlt:0,'Prüfen':1,Erfüllt:2,'Nicht relevant':3}[v]??9)}
function fp106SafeJson(v,fallback={}){try{return JSON.parse(v)}catch{return fallback}}
function fp106Url(v=''){const s=String(v||'').trim();return /^https:\/\//i.test(s)?s:''}
function fp106AreaPath(id,byId){const names=[],seen=new Set();let cur=byId[String(id)],n=0;while(cur&&!seen.has(String(cur.id))&&n++<20){seen.add(String(cur.id));names.unshift(cur.fields.Name||cur.fields.Title||'Gebiet');cur=cur.fields.ParentGebietId?byId[String(cur.fields.ParentGebietId)]:null}return names.join(' › ')}
function fp106Bool(v){return v===true}
function fp106Num(v){return v==null||v===''?null:Number(v)}
function fp106ResearchUrl(){return String(localStorage.getItem(FP106_URL_KEY)||'').trim().replace(/\/+$/,'')}
function fp106ResearchToken(){return String(localStorage.getItem(FP106_TOKEN_KEY)||'').trim()}

async function fp106FetchResearch(path,options={}){
  const base=fp106ResearchUrl();if(!base)throw new Error('Online-Recherche ist noch nicht eingerichtet. Unter Einstellungen die Research-Service-URL eintragen.');
  const token=fp106ResearchToken(),headers={...(options.headers||{}),'Content-Type':'application/json'};if(token)headers['X-Mobimory-Token']=token;
  const res=await fetch(base+path,{...options,headers});let body={};try{body=await res.json()}catch{body={error:await res.text().catch(()=>res.statusText)}}
  if(!res.ok)throw new Error(body?.error||body?.message||`Research Service: HTTP ${res.status}`);return body;
}
async function fp106TestResearchService(){
  const out=document.getElementById('fp106ResearchState');if(out)out.textContent='Verbindung wird geprüft …';
  try{const r=await fp106FetchResearch('/health',{method:'GET',headers:{}});if(out){out.className='status-ok';out.textContent=`✓ Research Service erreichbar · ${r.provider||'Provider'} · ${r.model||'Modell konfiguriert'}`}}
  catch(e){if(out){out.className='status-stop';out.textContent=e.message}}
}
function fp106SaveResearchSettings(){
  localStorage.setItem(FP106_URL_KEY,document.getElementById('fp106ResearchUrl')?.value.trim()||'');
  localStorage.setItem(FP106_TOKEN_KEY,document.getElementById('fp106ResearchToken')?.value.trim()||'');
  fp106TestResearchService();
}

/* Einstellungen um Research Service ergänzen. */
const fp106SettingsBase=settings;
settings=function(){
  fp106SettingsBase();
  const card=document.createElement('div');card.className='card';card.id='fp106-research-settings';
  card.innerHTML=`<div class="section first">Online-Recherche</div><p class="muted">Der Research Service hält den API-Schlüssel außerhalb der öffentlichen PWA und recherchiert aktuelle Quellen.</p>
    <div class="field"><label>Research-Service-URL</label><input id="fp106ResearchUrl" value="${esc(fp106ResearchUrl())}" placeholder="https://mobimory-research.…workers.dev"></div>
    <div class="field"><label>Zugriffstoken</label><input id="fp106ResearchToken" type="password" value="${esc(fp106ResearchToken())}" autocomplete="off"></div>
    <div class="actions"><button class="primary" onclick="fp106SaveResearchSettings()">Speichern & Verbindung testen</button></div><div id="fp106ResearchState" class="muted"></div>`;
  app.prepend(card);
};

async function travelcheck(){
  head('Reisecheck','Aktuell online recherchieren · automatisch mit deinen Daten abgleichen');app.innerHTML='<div class="card">Reisedaten werden geladen …</div>';
  try{
    const api=await getCloud(),[vs,ps,animals,areas,checks]=await Promise.all([fp105SafeList(api,'Fahrzeuge'),fp105SafeList(api,'Personen'),fp105SafeList(api,'Tiere'),fp105SafeList(api,'Gebiete'),fp105SafeList(api,'Reisechecks')]);
    const activeV=vs.filter(x=>x.fields.Aktiv!==false),activeP=ps.filter(x=>x.fields.Aktiv!==false),activeA=animals.filter(x=>x.fields.Aktiv!==false),activeG=areas.filter(x=>x.fields.Aktiv!==false),byId=Object.fromEntries(activeG.map(x=>[String(x.id),x]));
    FP106.data={vs,ps,animals,areas:activeG,byId};const now=new Date(),later=new Date(now.getTime()+7*86400000),loc=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),vm=Object.fromEntries(vs.map(v=>[String(v.id),v.fields.Fahrzeugname||v.fields.Title]));
    app.innerHTML=`<div class="card"><div class="section first">Reise</div>
      <div class="field"><label>Titel (optional)</label><input id="tcTitle" placeholder="z. B. Elsass 2026"></div>
      <div class="grid compact"><div class="field"><label>Beginn</label><input id="tcStart" type="date" value="${loc(now)}"></div><div class="field"><label>Ende</label><input id="tcEnd" type="date" value="${loc(later)}"></div></div>
      <div class="field"><label>Fahrzeug</label><select id="tcVehicle" onchange="fp106SuggestModes()">${activeV.map(v=>`<option value="${v.id}" data-profile="${esc(v.fields.Profil||'')}">${esc(v.fields.Fahrzeugname||v.fields.Title)} · ${esc(v.fields.Profil||v.fields.Fahrzeugtyp||'')}</option>`).join('')}</select></div>
      <div class="section">Verkehrsart</div><div class="chips"><label class="person-tile"><input type="checkbox" data-tcmode="Strasse"> Straße</label><label class="person-tile"><input type="checkbox" data-tcmode="Binnen"> Binnen</label><label class="person-tile"><input type="checkbox" data-tcmode="See"> See</label><label class="person-tile"><input type="checkbox" data-tcmode="Sonderrevier"> Sonderrevier</label></div>
      <div class="section">Mitreisende Personen</div>${activeP.map(p=>`<label class="person-tile"><input type="checkbox" data-tcperson="${p.id}"> ${esc(p.fields.Anzeigename||p.fields.Title)} · ${esc(p.fields.Rolle||'')}</label>`).join('')||'<p class="muted">Keine aktiven Personen.</p>'}
      <div class="section">Mitreisende Tiere</div>${activeA.map(a=>`<label class="person-tile"><input type="checkbox" data-tcanimal="${a.id}"> ${esc(a.fields.Name||a.fields.Title)} · ${esc(a.fields.Tierart||'')}</label>`).join('')||'<p class="muted">Keine aktiven Tiere.</p>'}
      <div class="section">Ziele / Länder / Reviere</div><p class="muted">Mehrfachauswahl möglich. Die Gebietshierarchie wird an die Recherche übergeben.</p>${activeG.sort((a,b)=>fp106AreaPath(a.id,byId).localeCompare(fp106AreaPath(b.id,byId),'de')).map(g=>`<label class="person-tile"><input type="checkbox" data-tcarea="${g.id}"> ${esc(fp106AreaPath(g.id,byId))}</label>`).join('')||'<p class="muted">Noch keine Gebiete/Reviere angelegt.</p>'}
      <button class="primary" onclick="runTravelCheck106()">Aktuell online recherchieren & prüfen</button><div id="tcResearchState" class="muted"></div>
    </div><div id="tcResult"></div>
    <div class="card"><div class="section first">Gespeicherte Reisechecks</div>${checks.sort((a,b)=>String(b.fields.ErstelltAm||'').localeCompare(String(a.fields.ErstelltAm||''))).slice(0,12).map(c=>`<button class="menu" onclick="S.travelCheckDetailId='${c.id}';go('travelcheckdetail')"><b>${esc(c.fields.Titel||c.fields.Title||'Reisecheck')}</b><span class="muted">${fp106DateTime(c.fields.OnlineRecherchiertAm||c.fields.ErstelltAm)} · ${esc(c.fields.Status||'')}</span><span>${esc(vm[String(c.fields.FahrzeugId)]||'')}</span></button>`).join('')||'<p class="muted">Noch kein Reisecheck gespeichert.</p>'}</div>
    <div class="card status-warn"><b>Planungshilfe</b><p>Aktuelle Online-Recherche reduziert veraltete Annahmen, ersetzt aber keine behördliche Einzelfallentscheidung. Quellen und Unsicherheiten bleiben sichtbar.</p></div>`;
    fp106SuggestModes();
    if(!fp106ResearchUrl()){const s=document.getElementById('tcResearchState');if(s){s.className='status-warn';s.innerHTML='Online-Recherche noch nicht eingerichtet. <button onclick="go(\'settings\')">Einstellungen öffnen</button>'}}
  }catch(e){failBox(e,'configuration')}
}
function fp106SuggestModes(){
  const sel=document.getElementById('tcVehicle');if(!sel)return;const profile=sel.options[sel.selectedIndex]?.dataset?.profile||'';
  document.querySelectorAll('[data-tcmode]').forEach(x=>x.checked=false);if(/wohnmobil/i.test(profile)){const x=document.querySelector('[data-tcmode="Strasse"]');if(x)x.checked=true}else if(/motorboot/i.test(profile)){for(const k of ['Binnen','See']){const x=document.querySelector(`[data-tcmode="${k}"]`);if(x)x.checked=true}}
}

async function fp106BuildResearchPayload(){
  const api=await getCloud(),vehicle=await api.getItemByName('Fahrzeuge',tcVehicle.value),personIds=fp106Selected('tcperson'),animalIds=fp106Selected('tcanimal'),areaIds=fp106Selected('tcarea'),modes=fp106Selected('tcmode');
  const [features,components,checks,vehicleRules,functions,quals,proofs]=await Promise.all([fp105SafeList(api,'Fahrzeugmerkmale'),fp105SafeList(api,'Komponenten'),fp105SafeList(api,'Pruefungen'),fp105SafeList(api,'FahrzeugBerechtigungsRegeln'),fp105SafeList(api,'PersonFunktionen'),fp105SafeList(api,'Befaehigungen'),fp105SafeList(api,'TierNachweise')]);
  const byId=FP106.data.byId,people=FP106.data.ps,animals=FP106.data.animals;FP106.subjectMap={vehicle:vehicle.fields.Fahrzeugname||vehicle.fields.Title||'Fahrzeug',trip:'Reise'};
  const pRows=personIds.map((id,i)=>{const key=`P${i+1}`,p=people.find(x=>String(x.id)===String(id));FP106.subjectMap[key]=p?.fields?.Anzeigename||p?.fields?.Title||`Person ${i+1}`;return {key,role:p?.fields?.Rolle||'',functions:functions.filter(x=>String(x.fields.PersonId)===String(id)&&x.fields.Aktiv!==false).map(x=>x.fields.Funktion),qualifications:quals.filter(x=>String(x.fields.PersonId)===String(id)&&x.fields.Aktiv!==false).map(x=>({type:x.fields.Art||'',present:x.fields.Vorhanden!==false,validFrom:x.fields.GueltigVon||null,validTo:x.fields.GueltigBis||null}))}});
  const aRows=animalIds.map((id,i)=>{const key=`A${i+1}`,a=animals.find(x=>String(x.id)===String(id));FP106.subjectMap[key]=a?.fields?.Name||a?.fields?.Title||`Tier ${i+1}`;return {key,species:a?.fields?.Tierart||'',hasChip:!!a?.fields?.Chipnummer,hasPetPassport:!!a?.fields?.HeimtierausweisNr,proofs:proofs.filter(x=>String(x.fields.TierId)===String(id)&&x.fields.Aktiv!==false).map(x=>({type:x.fields.Art||'',status:x.fields.Status||(x.fields.Vorhanden===false?'Fehlt':'Vorhanden'),issued:x.fields.Ausstellungsdatum||null,validFrom:x.fields.GueltigVon||null,validTo:x.fields.GueltigBis||null,result:x.fields.WertErgebnis||''}))}});
  const vf=vehicle.fields||{},ownFeat=features.filter(x=>String(x.fields.FahrzeugId)===String(vehicle.id)&&x.fields.Aktiv!==false),ownComp=components.filter(x=>String(x.fields.FahrzeugId)===String(vehicle.id)&&x.fields.Aktiv!==false),ownChecks=checks.filter(x=>String(x.fields.FahrzeugId)===String(vehicle.id)&&x.fields.Aktiv!==false),ownRules=vehicleRules.filter(x=>String(x.fields.FahrzeugId)===String(vehicle.id)&&x.fields.Aktiv!==false);
  const vehiclePublic={key:'vehicle',profile:vf.Profil||'',type:vf.Fahrzeugtyp||'',manufacturer:vf.Hersteller||'',model:vf.Modell||'',year:fp106Num(vf.Baujahr),firstRegistration:vf.Erstzulassung||null,lengthM:fp106Num(vf.Laenge),widthM:fp106Num(vf.Breite),heightM:fp106Num(vf.Hoehe),draftM:fp106Num(vf.Tiefgang),clearanceM:fp106Num(vf.Durchfahrtshoehe),emptyWeightKg:fp106Num(vf.Leergewicht),grossWeightKg:fp106Num(vf.ZulaessigesGesamtgewicht),axles:fp106Num(vf.Achsen),fuel:vf.Kraftstoff||'',hasRegistrationIdentifier:!!vf.KennzeichenRegistrierung,hasRegistrationDocument:!!vf.ZulassungsDokNr,hasVIN:!!vf.FIN_VIN,hasHIN:!!vf.HIN_CIN,features:ownFeat.map(x=>({name:x.fields.Merkmal||'',text:x.fields.WertText||'',number:fp106Num(x.fields.WertZahl),unit:x.fields.Einheit||''})),components:ownComp.map(x=>({type:x.fields.KomponentenTyp||x.fields.Typ||'',name:x.fields.Name||'',manufacturer:x.fields.Hersteller||'',model:x.fields.Modell||'',year:fp106Num(x.fields.Baujahr),installed:x.fields.Einbaudatum||null})),inspections:ownChecks.map(x=>({type:x.fields.Art||'',result:x.fields.Ergebnis||'',last:x.fields.LetztePruefung||x.fields.GeprueftAm||null,next:x.fields.NaechsterTermin||x.fields.GueltigBis||null})),qualificationRules:ownRules.map(x=>({ruleType:x.fields.Regelart||'',requiredProof:x.fields.NachweisArt||'',level:x.fields.Pflichtgrad||'',condition:x.fields.Bedingung||''}))};
  return {trip:{title:tcTitle.value.trim()||'Reisecheck',start:fp106Iso(tcStart.value),end:fp106Iso(tcEnd.value,true),trafficModes:modes,areas:areaIds.map(id=>{const g=byId[String(id)];return {key:String(id),name:g?.fields?.Name||g?.fields?.Title||'',type:g?.fields?.Gebietstyp||'',path:fp106AreaPath(id,byId)}})},vehicle:vehiclePublic,persons:pRows,animals:aRows,locale:'de-DE',researchPolicy:{currentWebResearchRequired:true,preferOfficialSources:true,officialSourcesForMandatoryItems:true,uncertaintyMustBeVisible:true,doNotInferComplianceWhenEvidenceIsMissing:true}};
}

async function runTravelCheck106(){
  const out=document.getElementById('tcResult'),state=document.getElementById('tcResearchState');if(!out)return;
  const areaIds=fp106Selected('tcarea');if(!areaIds.length)return alert('Mindestens ein Ziel / Land / Gebiet / Revier auswählen.');if(!tcStart.value||!tcEnd.value)return alert('Reisebeginn und Reiseende eingeben.');if(new Date(tcEnd.value)<new Date(tcStart.value))return alert('Reiseende liegt vor dem Reisebeginn.');if(!fp106ResearchUrl())return alert('Bitte zuerst unter Einstellungen den Research Service einrichten.');
  out.innerHTML='<div class="card">Aktuelle Regeln und Hinweise werden online recherchiert …</div>';if(state){state.className='muted';state.textContent='Web-Recherche läuft. Das kann etwas dauern …'}
  try{
    const payload=await fp106BuildResearchPayload(),r=await fp106FetchResearch('/research',{method:'POST',body:JSON.stringify(payload)}),result=r.result||{};
    if(!Array.isArray(result.requirements))throw new Error('Research Service hat keine strukturierten Anforderungen geliefert.');
    const rows=result.requirements.map((x,i)=>({...x,id:x.id||`R${i+1}`,subjectName:FP106.subjectMap[x.subjectKey]||x.subjectKey||x.subjectType||'Reise',sources:Array.isArray(x.sources)?x.sources:[]}));
    rows.sort((a,b)=>fp106CatOrder(a.category)-fp106CatOrder(b.category)||fp106StatusOrder(a.status)-fp106StatusOrder(b.status)||String(a.area||'').localeCompare(String(b.area||''),'de'));
    FP106.last={title:payload.trip.title||`${FP106.subjectMap.vehicle} · Reisecheck`,vehicleId:String(tcVehicle.value),start:payload.trip.start,end:payload.trip.end,areaIds:fp106Selected('tcarea'),personIds:fp106Selected('tcperson'),animalIds:fp106Selected('tcanimal'),modes:fp106Selected('tcmode'),researchedAt:r.researchedAt||new Date().toISOString(),provider:r.provider||'OpenAI',model:r.model||'',requestId:r.requestId||'',researchStatus:result.researchStatus||'teilweise',summary:result.summary||'',warnings:Array.isArray(result.warnings)?result.warnings:[],rows,raw:result};
    if(state){state.className='status-ok';state.textContent=`✓ Online-Recherche abgeschlossen · ${FP106.last.provider}${FP106.last.model?' · '+FP106.last.model:''} · ${fp106DateTime(FP106.last.researchedAt)}`}
    fp106RenderResult();
  }catch(e){if(state){state.className='status-stop';state.textContent=e.message}out.innerHTML=`<div class="card status-stop"><b>Online-Recherche fehlgeschlagen</b><p>${esc(e.message)}</p><button onclick="go('settings')">Research Service prüfen</button></div>`}
}
function fp106SourceHtml(s){const url=fp106Url(s?.url||''),meta=[s?.publisher,s?.updated].filter(Boolean).map(esc).join(' · '),official=s?.official?' · offiziell':'';return `<div class="muted">${s?.title?`<b>${esc(s.title)}</b> · `:''}${meta}${official}${url?` · <a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Quelle öffnen</a>`:''}</div>`}
function fp106RequirementHtml(x,i,editable=true){return `<div class="entitybox ${fp106StatusClass(x.status)}"><div class="line"><div><b>${esc(x.category||'')} · ${esc(x.requirement||'')}</b><div class="muted">${esc(x.area||'')} ${x.trafficMode?'· '+esc(x.trafficMode):''} · ${esc(x.subjectName||'')}</div></div><b>${esc(x.status||'Prüfen')}</b></div>${x.proofKey?`<div class="muted">Prüfschlüssel: ${esc(x.proofKey)}</div>`:''}<p>${esc(x.evidence||x.explanation||'')}</p>${x.explanation&&x.evidence?`<p class="muted">${esc(x.explanation)}</p>`:''}${(x.sources||[]).map(fp106SourceHtml).join('')||'<div class="muted">Keine belastbare Quelle geliefert.</div>'}<div class="muted">Recherche-Sicherheit: ${esc(x.confidence||'')} ${x.conflict?'· ⚠ Quellen-/Regelkonflikt':''}</div>${editable?`<div class="grid compact"><select onchange="fp106SetResult(${i},this.value)">${['Erfüllt','Fehlt','Prüfen','Nicht relevant'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select><button onclick="fp106AddNote(${i})">Notiz / Korrektur</button></div>`:''}</div>`}
function fp106RenderResult(){const out=document.getElementById('tcResult'),d=FP106.last;if(!out||!d)return;const counts=Object.fromEntries(['Erfüllt','Fehlt','Prüfen','Nicht relevant'].map(s=>[s,d.rows.filter(x=>x.status===s).length])),official=d.rows.flatMap(x=>x.sources||[]).filter(s=>s.official).length,sources=d.rows.flatMap(x=>x.sources||[]).length;out.innerHTML=`<div class="card ${counts.Fehlt?'status-stop':counts['Prüfen']?'status-warn':'status-ok'}"><div class="section first">${esc(d.title)}</div><p>${fp106Date(d.start)} bis ${fp106Date(d.end)} · online recherchiert ${fp106DateTime(d.researchedAt)}</p><div class="chips"><span>✓ Erfüllt ${counts.Erfüllt}</span><span>✕ Fehlt ${counts.Fehlt}</span><span>○ Prüfen ${counts['Prüfen']}</span><span>– Nicht relevant ${counts['Nicht relevant']}</span></div><p>${esc(d.summary||'')}</p><p class="muted">${sources} Quellenangabe(n), davon ${official} als offiziell gekennzeichnet · Recherchestatus: ${esc(d.researchStatus)}</p>${d.warnings?.length?`<div class="status-warn">${d.warnings.map(w=>`<div>${esc(w)}</div>`).join('')}</div>`:''}<button class="primary" onclick="saveTravelCheck106()">Reisecheck speichern</button></div><div class="card"><div class="section first">Aktuelle Anforderungen & Hinweise</div>${d.rows.map((x,i)=>fp106RequirementHtml(x,i,true)).join('')||'<p class="muted">Keine Anforderungen geliefert.</p>'}</div>`}
function fp106SetResult(i,v){const x=FP106.last?.rows?.[i];if(!x)return;x.status=v;x.manual=true;fp106RenderResult()}
function fp106AddNote(i){const x=FP106.last?.rows?.[i];if(!x)return;const n=prompt('Eigene Notiz / Korrektur:',x.userNote||'');if(n===null)return;x.userNote=n;x.manual=true;fp106RenderResult()}

async function saveTravelCheck106(){
  const d=FP106.last;if(!d)return;try{
    const api=await getCloud(),status=d.rows.some(x=>x.status==='Fehlt'||x.status==='Prüfen')?'Unvollstaendig':'Vollstaendig',sources=d.rows.flatMap(x=>(x.sources||[]).map(s=>({requirementId:x.id,title:s.title||'',url:s.url||'',publisher:s.publisher||'',official:!!s.official,updated:s.updated||''}))),snap={title:d.title,start:d.start,end:d.end,areas:d.areaIds,persons:d.personIds,animals:d.animalIds,modes:d.modes,summary:d.summary,warnings:d.warnings};
    const h=await api.createItemByName('Reisechecks',{Title:d.title,Titel:d.title,NutzungId:String(S.usage?.cloudId||'PLANUNG'),FahrzeugId:d.vehicleId,ErstelltAm:new Date().toISOString(),ReiseBeginn:d.start,ReiseEnde:d.end,GebietIds:d.areaIds.join('|'),PersonIds:d.personIds.join('|'),TierIds:d.animalIds.join('|'),Verkehrsarten:d.modes.join('|'),OnlineRecherchiertAm:d.researchedAt,RechercheProvider:d.provider,RechercheModell:d.model,RechercheRequestId:d.requestId,RechercheStatus:d.researchStatus,RechercheSnapshot:JSON.stringify(snap),QuellenSnapshot:JSON.stringify(sources),Status:status,Testdaten:testFlag()});
    for(const x of d.rows){const src=(x.sources||[])[0]||{};await api.createItemByName('ReisecheckPunkte',{ReisecheckId:String(h.id),GebietsAnforderungId:'',SubjektTyp:x.subjectType||'Reise',SubjektId:x.subjectKey||'',SubjektKey:x.subjectKey||'',SubjektName:x.subjectName||'',GebietName:x.area||'',Anforderung:x.requirement||'',Ergebnis:fp106OldResult(x.status),Status106:x.status,Kategorie106:x.category||'',Verkehrsart:x.trafficMode||'',NachweisArt:x.proofKey||'',Begruendung:[x.evidence,x.explanation,x.userNote].filter(Boolean).join(' · '),QuelleTitel:src.title||'',QuelleUrl:src.url||'',QuellePublisher:src.publisher||'',QuelleStand:src.updated||'',QuelleOffiziell:!!src.official,Confidence:x.confidence||'',Konflikt:!!x.conflict,AutomatischBewertet:!x.manual,BestaetigtAm:x.manual?new Date().toISOString():null,Notiz:x.userNote||'',Testdaten:testFlag()})}
    alert('Reisecheck mit Recherche- und Quellenstand gespeichert.');S.travelCheckDetailId=String(h.id);go('travelcheckdetail');
  }catch(e){alert('Reisecheck konnte nicht gespeichert werden: '+e.message+'\n\nBitte Microsoft 365 Setup für Version 1.0.6 ausführen.')}
}

async function travelcheckdetail(){
  head('Reisecheck','Gespeicherter Recherche- und Quellenstand');app.innerHTML='<div class="card">Reisecheck wird geladen …</div>';
  try{const api=await getCloud(),h=await api.getItemByName('Reisechecks',S.travelCheckDetailId),pts=(await fp105SafeList(api,'ReisecheckPunkte')).filter(x=>String(x.fields.ReisecheckId)===String(S.travelCheckDetailId)),rows=pts.map(p=>{const f=p.fields,s=f.Status106||fp106NewResult(f.Ergebnis);return {id:p.id,category:f.Kategorie106||'',requirement:f.Anforderung||'',area:f.GebietName||'',trafficMode:f.Verkehrsart||'',subjectName:f.SubjektName||f.SubjektTyp||'',subjectKey:f.SubjektKey||f.SubjektId||'',status:s,proofKey:f.NachweisArt||'',evidence:f.Begruendung||f.Notiz||'',explanation:'',confidence:f.Confidence||'',conflict:!!f.Konflikt,userNote:f.Notiz||'',sources:f.QuelleUrl?[{title:f.QuelleTitel||'',url:f.QuelleUrl||'',publisher:f.QuellePublisher||'',updated:f.QuelleStand||'',official:!!f.QuelleOffiziell}]:[]}}),counts=Object.fromEntries(['Erfüllt','Fehlt','Prüfen','Nicht relevant'].map(s=>[s,rows.filter(x=>x.status===s).length])),snap=fp106SafeJson(h.fields.RechercheSnapshot||'{}',{});app.innerHTML=`<div class="card ${counts.Fehlt?'status-stop':counts['Prüfen']?'status-warn':'status-ok'}"><div class="section first">${esc(h.fields.Titel||h.fields.Title||'Reisecheck')}</div><p>${fp106Date(h.fields.ReiseBeginn)} bis ${fp106Date(h.fields.ReiseEnde)}</p><div class="chips"><span>✓ ${counts.Erfüllt}</span><span>✕ ${counts.Fehlt}</span><span>○ ${counts['Prüfen']}</span><span>– ${counts['Nicht relevant']}</span></div><p>${esc(snap.summary||'')}</p><p class="muted">Online recherchiert ${fp106DateTime(h.fields.OnlineRecherchiertAm)} · ${esc(h.fields.RechercheProvider||'')} ${esc(h.fields.RechercheModell||'')} · ${esc(h.fields.RechercheStatus||'')}</p><div class="actions"><button class="danger-lite" onclick="fp106DeleteCheck('${h.id}')">Reisecheck löschen</button></div></div><div class="card"><div class="section first">Gespeicherte Prüfpunkte</div>${rows.sort((a,b)=>fp106CatOrder(a.category)-fp106CatOrder(b.category)).map((x,i)=>`<div id="rcp-${x.id}">${fp106RequirementHtml(x,i,false)}<div class="grid compact"><select id="rcs-${x.id}">${['Erfüllt','Fehlt','Prüfen','Nicht relevant'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select><button onclick="fp106UpdatePoint('${x.id}')">Manuell bewerten</button></div></div>`).join('')||'<p class="muted">Keine Prüfpunkte.</p>'}</div>`}catch(e){failBox(e,'travelcheck')}
}
async function fp106UpdatePoint(id){try{const api=await getCloud(),p=await api.getItemByName('ReisecheckPunkte',id),v=document.getElementById('rcs-'+id)?.value||'Prüfen',n=prompt('Notiz / Begründung:',p.fields.Notiz||'');if(n===null)return;await api.updateItemByName('ReisecheckPunkte',id,{Status106:v,Ergebnis:fp106OldResult(v),AutomatischBewertet:false,BestaetigtAm:new Date().toISOString(),Notiz:n});const all=(await fp105SafeList(api,'ReisecheckPunkte')).filter(x=>String(x.fields.ReisecheckId)===String(S.travelCheckDetailId)),status=all.some(x=>{const s=String(x.id)===String(id)?v:(x.fields.Status106||fp106NewResult(x.fields.Ergebnis));return s==='Fehlt'||s==='Prüfen'})?'Unvollstaendig':'Vollstaendig';await api.updateItemByName('Reisechecks',S.travelCheckDetailId,{Status:status});await travelcheckdetail()}catch(e){alert(e.message)}}
async function fp106DeleteCheck(id){if(!confirm('Reisecheck und Prüfpunkte wirklich löschen?'))return;try{const api=await getCloud(),pts=(await fp105SafeList(api,'ReisecheckPunkte')).filter(x=>String(x.fields.ReisecheckId)===String(id));for(const p of pts)await api.deleteItemByName('ReisecheckPunkte',p.id);await api.deleteItemByName('Reisechecks',id);S.stack=[];S.view='travelcheck';render()}catch(e){alert(e.message)}}

/* Schema + Renderer + Version */
const fp106MergedSchemaBase=fp105MergedSchema;
fp105MergedSchema=async function(){const [prior,e106]=await Promise.all([fp106MergedSchemaBase(),fetch('phase1-sharepoint-schema-1.0.6.json',{cache:'no-store'}).then(r=>r.json())]);return fp105MergeSchemas(prior,e106)};
const fp106RenderBase=render;render=function(){if(S.view==='travelcheckdetail')return travelcheckdetail();return fp106RenderBase()};
m365setup=function(){head('Microsoft 365 Setup','Schema 1.0.6 · Online-Reisecheck · additiv');const tok=window.FPAuth.token(),authButton=tok?`<button onclick="FPAuth.logout();render()">Microsoft-Verbindung trennen</button>`:`<button class="primary" onclick="sessionStorage.setItem('fp_after_auth','m365setup');FPAuth.login()">Mit Microsoft 365 anmelden</button>`;app.innerHTML=`<div class="card"><b>Microsoft-Anmeldung</b><div id="authState">${tok?'✓ Microsoft-Token vorhanden':'Noch nicht mit Microsoft verbunden'}</div>${authButton}</div><div class="card"><div class="field"><label>SharePoint-Site-URL</label><input id="spSite" value="${esc(localStorage.getItem('fp_sp_site')||'')}" placeholder="https://…sharepoint.com/sites/Fahrzeugplattform"></div><button class="primary" ${tok?'':'disabled'} onclick="runM365Provision106()">Phase-1-Struktur prüfen / anlegen</button><p class="muted">Additiv und wiederholbar. 1.0.6 ergänzt nur Recherche-, Quellen- und Bewertungsfelder.</p></div><div id="m365Result"></div>`};
async function runM365Provision106(){const url=document.getElementById('spSite').value.trim();if(!url)return alert('Bitte die vollständige SharePoint-Site-URL eintragen.');localStorage.setItem('fp_sp_site',url);const out=document.getElementById('m365Result');out.innerHTML='<div class="card">Schema 1.0.6 wird geladen …</div>';try{const schema=await fp105MergedSchema(),setup=new FPGraphSetup(FPAuth.token(),url,schema),site=await setup.resolveSite();let lines=[];out.innerHTML=`<div class="card"><b>Verbunden:</b> ${esc(site.displayName)}<div id="provLog" class="muted">Prüfung startet …</div></div>`;const log=document.getElementById('provLog'),res=await setup.provision(e=>{if(e.status==='created')lines.push(`${e.kind==='list'?'Liste':'Feld'} angelegt: ${e.kind==='field'?e.list+' · ':''}${e.name}`);if(log)log.innerHTML=`Fortschritt: ${esc(e.kind==='field'?e.list+' · '+e.name:e.name)}<br>${lines.slice(-8).map(esc).join('<br>')}`});out.innerHTML=`<div class="card status-ok"><b>Setup abgeschlossen und verifiziert</b><p>${res.totalLists} Listen geprüft · ${res.listsCreated} neu angelegt · ${res.fieldsCreated} Felder neu angelegt · ${res.verifiedLists} Listen für die App erreichbar.</p></div>`}catch(e){out.innerHTML=`<div class="card status-stop"><b>Setup nicht abgeschlossen</b><p>${esc(e.message)}</p></div>`}}
runM365Provision=runM365Provision106;
exportPhase1Data=async function(){try{const schema=await fp105MergedSchema(),api=await getCloud(),data={exportedAt:new Date().toISOString(),version:FP106_VERSION,lists:{}};for(const l of schema.lists){try{data.lists[l.internalName]=await list(api,l.internalName)}catch(e){data.lists[l.internalName]={error:e.message}}}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Fahrzeugplattform_Export_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}};
login=function(){bar.hidden=true;app.innerHTML=`<div class="login"><div class="card mobi-login">${typeof mobiIcon==='function'?mobiIcon():''}${typeof brandHeadline==='function'?brandHeadline():'<div class="brand">MOBIMORY</div>'}<p class="muted">Version ${FP106_VERSION}</p><div class="field"><label>Nutzer</label><input value="Admin"></div><div class="field"><label>Passwort</label><input type="password" value="admin"></div><button class="primary" onclick="S.stack=[];S.view='main';render()">Anmelden</button></div></div>`};
document.title=`Fahrzeugplattform ${FP106_VERSION}`;const fp106Foot=document.querySelector('footer');if(fp106Foot)fp106Foot.textContent=`Fahrzeugplattform · ${FP106_VERSION} · © 2026 Entwicklungsstand`;try{render()}catch(e){console.warn(e)}
