/* MOBIMORY / Fahrzeugplattform 1.0.5-dev
   Ausbau: Orts-/Standortlernen, direkte Stammdatenerfassung, Ver-/Entsorgung,
   Online-Wetter, Tiere im Verleih und fahrzeugbezogene Berechtigungsregeln.
   Der automatische Online-Reisecheck ist bewusst NICHT Bestandteil dieser Version. */

const FP105_VERSION='1.0.5-dev';
const FP105={
  supplyRows:[],
  weatherSource:null,
  showWeatherManual:false,
  locationCache:null
};

function fp105SafeList(api,name){return list(api,name).catch(()=>[])}
function fp105Num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function fp105Money(v){return Number(v||0).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})}
function fp105NormText(v){return String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim()}
function fp105IsoLocalValue(v){return typeof fp104LocalInput==='function'?fp104LocalInput(v):(()=>{const d=new Date(v||Date.now());return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)})()}
function fp105Ctx(){return S.pendingContext||{timestamp:new Date().toISOString(),lat:null,lon:null,accuracy:null}}
function fp105Coords(prefix){
  const la=document.getElementById(prefix+'Lat'),lo=document.getElementById(prefix+'Lon'),ctx=fp105Ctx(),lat=la&&la.value!==''?Number(la.value):ctx.lat,lon=lo&&lo.value!==''?Number(lo.value):ctx.lon;
  return {lat:Number.isFinite(lat)?lat:null,lon:Number.isFinite(lon)?lon:null,accuracy:ctx.accuracy??null};
}
function fp105Distance(a,b,c,d){return typeof fp104DistM==='function'?fp104DistM(a,b,c,d):(()=>{const R=6371000,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),q=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))})()}

async function fp105LocationBundle(api,ctx=fp105Ctx()){
  const [orts,sites,learned,events,stays]=await Promise.all([
    fp105SafeList(api,'Orte'),fp105SafeList(api,'Standorte'),fp105SafeList(api,'PositionsOrtsHistorie'),fp105SafeList(api,'Ereignisse'),fp105SafeList(api,'Aufenthalte')
  ]);
  const om=Object.fromEntries(orts.map(x=>[String(x.id),x])),sm=Object.fromEntries(sites.map(x=>[String(x.id),x])),candidates=[];
  const push=(kind,id,ortId,lat,lon,priority,source)=>{
    lat=Number(lat);lon=Number(lon);if(ctx.lat==null||ctx.lon==null||!Number.isFinite(lat)||!Number.isFinite(lon))return;
    const d=fp105Distance(ctx.lat,ctx.lon,lat,lon),limits={0:300,1:600,2:1800,3:800,4:1800,5:5000},limit=limits[priority]??1500;if(d>limit)return;
    const item=kind==='site'?sm[String(id)]:om[String(id)],name=item?.fields?.Name||item?.fields?.Title||'';if(!item||!name)return;
    candidates.push({type:kind,id:String(id),ortId:String(ortId||item?.fields?.OrtId||''),name,distance:d,priority,score:d+priority*250,source});
  };
  for(const s of sites)push('site',s.id,s.fields.OrtId,s.fields.Breitengrad,s.fields.Laengengrad,0,'Standort-Stammdaten');
  for(const h of learned.filter(x=>x.fields.Aktiv!==false)){
    if(h.fields.StandortId)push('site',h.fields.StandortId,h.fields.OrtId,h.fields.Breitengrad,h.fields.Laengengrad,1,'frühere Verwendung');
    else if(h.fields.OrtId)push('ort',h.fields.OrtId,'',h.fields.Breitengrad,h.fields.Laengengrad,2,'frühere Verwendung');
  }
  /* 1.0.4-Bestandsdaten mitlernen, damit ein bereits gespeicherter Wohnmobil-Ort sofort auch beim Boot vorgeschlagen wird. */
  for(const x of [...events,...stays].filter(x=>x.fields.Aktiv!==false)){
    if(x.fields.StandortId)push('site',x.fields.StandortId,x.fields.OrtId,x.fields.Breitengrad,x.fields.Laengengrad,3,'früherer Vorgang');
    else if(x.fields.OrtId)push('ort',x.fields.OrtId,'',x.fields.Breitengrad,x.fields.Laengengrad,4,'früherer Vorgang');
  }
  for(const o of orts)push('ort',o.id,'',o.fields.Breitengrad,o.fields.Laengengrad,5,'Ort-Stammdaten');
  candidates.sort((a,b)=>a.score-b.score||a.distance-b.distance);
  return {orts,sites,near:candidates[0]||null};
}
function fp105LocationSuggestion(prefix,near){
  if(!near)return'';const dist=near.distance<1000?`${Math.round(near.distance)} m`:`${(near.distance/1000).toFixed(1)} km`;
  return `<div class="fp105-suggestion"><span><b>Vorschlag:</b> ${esc(near.name)} · ${dist}<small>${esc(near.source||'')}</small></span><button type="button" onclick="fp105ApplyLocation('${prefix}','${near.type}','${near.id}','${near.ortId||''}')">Übernehmen</button></div>`;
}
function fp105LocationBlock(prefix,orts,sites,near,label='Ort / Standort'){
  const types=['Hafen','Marina','Liegeplatz','Ankerplatz','Mooring','Stellplatz','Campingplatz','Parkplatz','Tankstelle','Werkstatt','Sonstiges'];
  return `<div class="fp105-location"><div class="section">${esc(label)}</div>
    <div class="fp105-loc-row"><select id="${prefix}Ort" onchange="fp105RefreshSites('${prefix}')"><option value="">– kein Ort –</option>${orts.filter(x=>x.fields.Aktiv!==false).map(x=>`<option value="${x.id}">${esc(x.fields.Name||x.fields.Title||'Ort')}</option>`).join('')}</select><button type="button" onclick="fp105ToggleNew('${prefix}','ort')">+ Ort</button></div>
    <div id="${prefix}NewOrt" class="fp105-inline-new" hidden><input id="${prefix}NewOrtName" placeholder="Neuen Ort eingeben"><button type="button" class="primary" onclick="fp105CreateOrt('${prefix}')">Ort speichern</button></div>
    <div class="fp105-loc-row"><select id="${prefix}Standort"><option value="">– kein Standort –</option>${sites.filter(x=>x.fields.Aktiv!==false).map(x=>`<option value="${x.id}" data-ort="${esc(String(x.fields.OrtId||''))}">${esc(x.fields.Name||x.fields.Title||'Standort')}</option>`).join('')}</select><button type="button" onclick="fp105ToggleNew('${prefix}','site')">+ Standort</button></div>
    <div id="${prefix}NewSite" class="fp105-inline-new" hidden><input id="${prefix}NewSiteName" placeholder="Neuen Standort eingeben"><select id="${prefix}NewSiteType">${types.map(x=>`<option>${x}</option>`).join('')}</select><button type="button" class="primary" onclick="fp105CreateStandort('${prefix}')">Standort speichern</button></div>
    ${fp105LocationSuggestion(prefix,near)}
  </div>`;
}
function fp105ToggleNew(prefix,kind){const e=document.getElementById(prefix+(kind==='ort'?'NewOrt':'NewSite'));if(e)e.hidden=!e.hidden}
function fp105RefreshSites(prefix){
  const o=document.getElementById(prefix+'Ort'),s=document.getElementById(prefix+'Standort');if(!s)return;const oid=o?.value||'',old=s.value;
  [...s.options].forEach((op,i)=>{if(i===0)return;op.hidden=!!oid&&String(op.dataset.ort||'')!==String(oid)});if(old&&s.selectedOptions[0]?.hidden)s.value='';
}
function fp105ApplyLocation(prefix,type,id,ortId){
  const o=document.getElementById(prefix+'Ort'),s=document.getElementById(prefix+'Standort');if(type==='ort'&&o)o.value=String(id);if(type==='site'){if(o&&ortId)o.value=String(ortId);fp105RefreshSites(prefix);if(s)s.value=String(id)}else fp105RefreshSites(prefix);
}
function fp105LocationValue(prefix){
  const oid=document.getElementById(prefix+'Ort')?.value||'',sid=document.getElementById(prefix+'Standort')?.value||'',d=S.locationData||{},o=(d.orts||[]).find(x=>String(x.id)===String(oid)),s=(d.sites||[]).find(x=>String(x.id)===String(sid));
  return {ortId:oid,standortId:sid,text:s?.fields?.Name||s?.fields?.Title||o?.fields?.Name||o?.fields?.Title||''};
}
async function fp105CreateOrt(prefix){
  const inp=document.getElementById(prefix+'NewOrtName');if(!inp?.value.trim())return alert('Ort eingeben.');
  try{const api=await getCloud(),c=fp105Coords(prefix),f={Title:inp.value.trim(),Name:inp.value.trim(),Aktiv:true,Verwendungen:1,ZuletztVerwendet:new Date().toISOString()};if(c.lat!=null){f.Breitengrad=c.lat;f.Laengengrad=c.lon;if(c.accuracy!=null)f.GenauigkeitM=c.accuracy}const x=await api.createItemByName('Orte',f),row={id:String(x.id),fields:f};S.locationData=S.locationData||{orts:[],sites:[]};S.locationData.orts.push(row);const sel=document.getElementById(prefix+'Ort'),op=document.createElement('option');op.value=row.id;op.textContent=f.Name;sel.appendChild(op);sel.value=row.id;inp.value='';document.getElementById(prefix+'NewOrt').hidden=true;fp105RefreshSites(prefix)}catch(e){alert('Ort konnte nicht angelegt werden: '+e.message)}
}
async function fp105CreateStandort(prefix){
  const name=document.getElementById(prefix+'NewSiteName'),typ=document.getElementById(prefix+'NewSiteType'),oid=document.getElementById(prefix+'Ort')?.value||'';if(!name?.value.trim())return alert('Standort eingeben.');if(!oid)return alert('Bitte zuerst einen Ort auswählen oder neu anlegen.');
  try{const api=await getCloud(),c=fp105Coords(prefix),f={Title:name.value.trim(),OrtId:String(oid),Name:name.value.trim(),Standorttyp:typ?.value||'Sonstiges',Aktiv:true};if(c.lat!=null){f.Breitengrad=c.lat;f.Laengengrad=c.lon;if(c.accuracy!=null)f.GenauigkeitM=c.accuracy}const x=await api.createItemByName('Standorte',f),row={id:String(x.id),fields:f};S.locationData=S.locationData||{orts:[],sites:[]};S.locationData.sites.push(row);const sel=document.getElementById(prefix+'Standort'),op=document.createElement('option');op.value=row.id;op.dataset.ort=String(oid);op.textContent=f.Name;sel.appendChild(op);sel.value=row.id;name.value='';document.getElementById(prefix+'NewSite').hidden=true}catch(e){alert('Standort konnte nicht angelegt werden: '+e.message)}
}
async function fp105RememberLocation(api,loc,ctx,sourceType,sourceId){
  if(ctx?.lat==null||ctx?.lon==null||(!loc?.ortId&&!loc?.standortId))return;try{await api.createItemByName('PositionsOrtsHistorie',{OrtId:String(loc.ortId||''),StandortId:String(loc.standortId||''),Breitengrad:Number(ctx.lat),Laengengrad:Number(ctx.lon),GenauigkeitM:ctx.accuracy==null?null:Number(ctx.accuracy),Zeitpunkt:ctx.timestamp||new Date().toISOString(),QuelleTyp:sourceType||'',QuelleId:String(sourceId||''),FahrzeugId:String(S.vehicle?.id||''),Testdaten:testFlag(),Aktiv:true})}catch(e){console.warn('Ortslernen nicht gespeichert',e)}
}

/* Cockpit-Bezeichnung modernisieren, ohne die stabile 1.0.4-Logik zu duplizieren. */
const fp105CockpitBase=cockpit;
cockpit=async function(){
  await fp105CockpitBase();
  const b=[...document.querySelectorAll('.secondary button')].find(x=>/Tanken|Versorgung/.test(x.textContent||''));if(b){b.textContent='Ver- / Entsorgung';b.onclick=()=>fp104CockpitAction('Ver- / Entsorgung','supply')}
};

/* Ereignis mit fahrzeugübergreifender Orts-/Standort-Erkennung und direktem Anlegen. */
event=async function(){
  head('Ereignis / Nachtrag',S.vehicle?.name||'Nutzung');
  try{
    const api=await getCloud(),ctx=fp105Ctx(),bundle=await fp105LocationBundle(api,ctx);S.locationData={orts:bundle.orts,sites:bundle.sites};
    const p=profileDef(),types=[...p.events];if(!types.includes('Wegpunkt / Position'))types.push('Wegpunkt / Position');if(!types.includes('Nachtrag / Sonstiges'))types.push('Nachtrag / Sonstiges');
    app.innerHTML=`<div class="card"><div class="field"><label>Ereignisart</label><select id="evType">${types.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div>
      <div class="fp-compact-time"><span><b>Zeitpunkt</b><small>beim Cockpit-Tipp erfasst · für Nachträge änderbar</small></span><input id="evWhen" type="datetime-local" value="${fp105IsoLocalValue(ctx.timestamp)}"></div>
      ${fp105LocationBlock('ev',bundle.orts,bundle.sites,bundle.near,'Ort / Standort')}
      <div class="fp-gps-line"><span>GPS</span><input id="evLat" type="number" step="0.000001" value="${ctx.lat??''}" placeholder="Breitengrad"><input id="evLon" type="number" step="0.000001" value="${ctx.lon??''}" placeholder="Längengrad">${ctx.accuracy?`<small>± ${Math.round(ctx.accuracy)} m</small>`:''}</div>
      <div class="field"><label>Bemerkung</label><textarea id="evNote"></textarea></div><button class="primary" onclick="saveEventV105()">Speichern</button></div>`;fp105RefreshSites('ev');
  }catch(e){failBox(e)}
};
async function saveEventV105(){
  try{
    const api=await getCloud(),loc=fp105LocationValue('ev'),c=fp105Coords('ev'),when=evWhen.value?new Date(evWhen.value).toISOString():(fp105Ctx().timestamp||new Date().toISOString()),now=new Date().toISOString(),isBackfill=Math.abs(new Date(now)-new Date(when))>5*60*1000,
      f={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day?.id||''),BenutzerId:'current',Art:evType.value,Zeitpunkt:when,ErfasstAm:now,Herkunft:isBackfill?'Nachtrag':'Manuell',Rohdaten:false,Notiz:evNote.value.trim(),OrtId:loc.ortId,StandortId:loc.standortId,Testdaten:testFlag(),Aktiv:true};if(c.lat!=null){f.Breitengrad=c.lat;f.Laengengrad=c.lon}const x=await api.createItemByName('Ereignisse',f);await fp105RememberLocation(api,loc,{timestamp:when,lat:c.lat,lon:c.lon,accuracy:c.accuracy},'Ereignis',x.id);S.pendingContext=null;back();
  }catch(e){alert(e.message)}
}
saveEventV104=saveEventV105;

/* Anlegen/Ankunft mit direkter Ort-/Standortpflege. */
stay=async function(){
  head(S.vehicle.profile==='motorboat'?'Anlegen / Ankern':'Ankunft / Parken',S.vehicle.name);
  try{const api=await getCloud(),ctx=fp105Ctx(),bundle=await fp105LocationBundle(api,ctx);S.locationData={orts:bundle.orts,sites:bundle.sites};app.innerHTML=`<div class="card"><div class="fp-compact-time"><span><b>Ankunft</b><small>beim Cockpit-Tipp erfasst</small></span><span>${fp104Date(ctx.timestamp)} · ${fp104Time(ctx.timestamp)}</span></div><div class="field"><label>Aufenthaltsart</label><select id="stType">${profileDef().stays.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div>${fp105LocationBlock('st',bundle.orts,bundle.sites,bundle.near,'Ort / Standort')}<div class="fp-gps-read">GPS: ${ctx.lat!=null?`${ctx.lat.toFixed(6)} · ${ctx.lon.toFixed(6)}${ctx.accuracy?` · ± ${Math.round(ctx.accuracy)} m`:''}`:'nicht verfügbar'}</div><button class="primary" onclick="saveStayV105()">Speichern</button></div>`;fp105RefreshSites('st')}catch(e){failBox(e)}
};
async function saveStayV105(){
  try{const api=await getCloud(),l=fp105LocationValue('st'),ctx=fp105Ctx(),f={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day.id),Art:stType.value,Ort:l.text,OrtId:l.ortId,StandortId:l.standortId,Beginn:ctx.timestamp,Testdaten:testFlag(),Aktiv:true};if(ctx.lat!=null){f.Breitengrad=ctx.lat;f.Laengengrad=ctx.lon;if(ctx.accuracy!=null)f.GenauigkeitM=ctx.accuracy}const x=await api.createItemByName('Aufenthalte',f);await fp105RememberLocation(api,l,ctx,'Aufenthalt',x.id);if(l.text){S.day.goal=l.text;try{await api.updateItemByName('Tagesetappen',S.day.id,{TatsaechlichesZiel:l.text})}catch{}const rec=JSON.parse(localStorage.getItem('fp-current')||'{}');if(rec.day){rec.day.goal=l.text;localStorage.setItem('fp-current',JSON.stringify(rec))}}S.pendingContext=null;back()}catch(e){alert(e.message)}
}
saveStayV104=saveStayV105;

/* Kontrolle mit Positionskontext und direkt pflegbaren Orten/Standorten. */
control=async function(){
  head('Kontrolle',S.vehicle.name);app.innerHTML='<div class="card">Prüfpunkte werden geladen …</div>';
  try{
    const api=await getCloud(),ctx=fp105Ctx(),rows=(await fp105SafeList(api,'FahrzeugPruefpunkte')).filter(x=>String(x.fields.FahrzeugId)===String(S.vehicle.id)&&x.fields.Aktiv!==false),bundle=await fp105LocationBundle(api,ctx);S.locationData={orts:bundle.orts,sites:bundle.sites};
    app.innerHTML=`<div class="card"><div class="fp-compact-time"><span><b>Kontrolle</b><small>Zeitpunkt/GPS beim Cockpit-Tipp erfasst</small></span><span>${fp104Date(ctx.timestamp)} · ${fp104Time(ctx.timestamp)}</span></div>${fp105LocationBlock('ct',bundle.orts,bundle.sites,bundle.near,'Ort / Standort')}${rows.map(x=>`<label class="checkrow"><input type="checkbox" data-check="${x.id}"> ${esc(x.fields.Name)}</label>`).join('')||'<p class="muted">Keine Prüfpunkte konfiguriert.</p>'}<textarea id="ctrlNote" placeholder="Ergebnis / Notiz"></textarea><button class="primary" onclick="saveControls105()">Kontrolle speichern</button></div>`;fp105RefreshSites('ct');
  }catch(e){failBox(e)}
};
async function saveControls105(){
  try{const api=await getCloud(),sel=[...document.querySelectorAll('[data-check]:checked')],ctx=fp105Ctx(),loc=fp105LocationValue('ct');if(!sel.length&&!ctrlNote.value.trim())return alert('Mindestens einen Prüfpunkt auswählen oder eine Notiz eingeben.');let firstId='';if(sel.length){for(const c of sel){const f={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day.id),PruefpunktId:c.dataset.check,BenutzerId:'current',AbgeschlossenAm:ctx.timestamp,Ergebnis:ctrlNote.value.trim()||'OK',OrtId:loc.ortId,StandortId:loc.standortId,Zeitpunkt:ctx.timestamp,Testdaten:testFlag(),Aktiv:true};if(ctx.lat!=null){f.Breitengrad=ctx.lat;f.Laengengrad=ctx.lon;if(ctx.accuracy!=null)f.GenauigkeitM=ctx.accuracy}const x=await api.createItemByName('Kontrollen',f);if(!firstId)firstId=x.id}}else{const f={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day.id),PruefpunktId:'',BenutzerId:'current',AbgeschlossenAm:ctx.timestamp,Ergebnis:ctrlNote.value.trim(),OrtId:loc.ortId,StandortId:loc.standortId,Zeitpunkt:ctx.timestamp,Testdaten:testFlag(),Aktiv:true};if(ctx.lat!=null){f.Breitengrad=ctx.lat;f.Laengengrad=ctx.lon;if(ctx.accuracy!=null)f.GenauigkeitM=ctx.accuracy}firstId=(await api.createItemByName('Kontrollen',f)).id}await fp105RememberLocation(api,loc,ctx,'Kontrolle',firstId);S.pendingContext=null;back()}catch(e){alert(e.message)}
}
saveControls=saveControls105;

/* Ver- / Entsorgung mit mehreren Positionen und optionalen Kosten je Position. */
function fp105SupplyDefaults(art){const m={Kraftstoff:['Aufnahme','l'],Frischwasser:['Aufnahme','l'],Abwasser:['Abgabe','l'],Fäkalien:['Abgabe','l'],'Strom / Laden':['Aufnahme','kWh'],Gas:['Aufnahme','kg'],Müll:['Abgabe',''],Sonstiges:['Aufnahme','']};return m[art]||['Aufnahme','']}
function fp105SupplyReadRows(){
  FP105.supplyRows=FP105.supplyRows.map((r,i)=>({art:document.getElementById('supArt'+i)?.value||r.art,richtung:document.getElementById('supDir'+i)?.value||r.richtung,menge:document.getElementById('supQty'+i)?.value||'',einheit:document.getElementById('supUnit'+i)?.value||'',kosten:document.getElementById('supCost'+i)?.value||'',waehrung:document.getElementById('supCur'+i)?.value||'EUR',komponenteId:document.getElementById('supComp'+i)?.value||'',notiz:document.getElementById('supNote'+i)?.value||''}));
}
function fp105SupplyRowsHtml(){const cs=S.supplyData?.components||[],arts=['Kraftstoff','Frischwasser','Abwasser','Fäkalien','Strom / Laden','Gas','Müll','Sonstiges'];return FP105.supplyRows.map((r,i)=>`<div class="fp105-supply-row"><div class="fp105-row-head"><b>Position ${i+1}</b>${FP105.supplyRows.length>1?`<button type="button" class="danger-lite" onclick="fp105RemoveSupplyRow(${i})">Entfernen</button>`:''}</div><div class="grid compact"><div class="field"><label>Art</label><select id="supArt${i}" onchange="fp105SupplyArtChanged(${i})">${arts.map(x=>`<option ${r.art===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Richtung</label><select id="supDir${i}"><option ${r.richtung==='Aufnahme'?'selected':''}>Aufnahme</option><option ${r.richtung==='Abgabe'?'selected':''}>Abgabe</option></select></div><div class="field"><label>Menge</label><input id="supQty${i}" type="number" step="0.01" value="${esc(r.menge)}"></div><div class="field"><label>Einheit</label><input id="supUnit${i}" value="${esc(r.einheit)}" placeholder="l / kWh / kg / Stück"></div><div class="field"><label>Kosten optional</label><input id="supCost${i}" type="number" step="0.01" value="${esc(r.kosten)}"></div><div class="field"><label>Währung</label><input id="supCur${i}" value="${esc(r.waehrung||'EUR')}"></div></div><div class="field"><label>Komponente / Tank optional</label><select id="supComp${i}"><option value="">– Fahrzeug allgemein –</option>${cs.map(x=>`<option value="${x.id}" ${String(r.komponenteId)===String(x.id)?'selected':''}>${esc(x.fields.Name||'')} · ${esc(x.fields.KomponentenTyp||x.fields.Typ||'')}</option>`).join('')}</select></div><div class="field"><label>Positionsnotiz optional</label><input id="supNote${i}" value="${esc(r.notiz||'')}"></div></div>`).join('')}
function fp105RenderSupplyRows(){const h=document.getElementById('fp105SupplyRows');if(h)h.innerHTML=fp105SupplyRowsHtml();fp105UpdateSupplyTotal()}
function fp105AddSupplyRow(){fp105SupplyReadRows();FP105.supplyRows.push({art:'Frischwasser',richtung:'Aufnahme',menge:'',einheit:'l',kosten:'',waehrung:'EUR',komponenteId:'',notiz:''});fp105RenderSupplyRows()}
function fp105RemoveSupplyRow(i){fp105SupplyReadRows();FP105.supplyRows.splice(i,1);if(!FP105.supplyRows.length)FP105.supplyRows.push({art:'Kraftstoff',richtung:'Aufnahme',menge:'',einheit:'l',kosten:'',waehrung:'EUR',komponenteId:'',notiz:''});fp105RenderSupplyRows()}
function fp105SupplyArtChanged(i){fp105SupplyReadRows();const d=fp105SupplyDefaults(FP105.supplyRows[i].art);FP105.supplyRows[i].richtung=d[0];FP105.supplyRows[i].einheit=d[1];fp105RenderSupplyRows()}
function fp105UpdateSupplyTotal(){const el=document.getElementById('fp105SupplyTotal');if(!el)return;let t=0;for(let i=0;i<FP105.supplyRows.length;i++)t+=Number(document.getElementById('supCost'+i)?.value||FP105.supplyRows[i].kosten||0);el.textContent=`Gesamtkosten: ${fp105Money(t)} €`}
supply=async function(){
  head('Ver- / Entsorgung',S.vehicle.name);app.innerHTML='<div class="card">Daten werden geladen …</div>';
  try{const api=await getCloud(),ctx=fp105Ctx(),components=(await fp105SafeList(api,'Komponenten')).filter(x=>String(x.fields.FahrzeugId)===String(S.vehicle.id)&&x.fields.Aktiv!==false),bundle=await fp105LocationBundle(api,ctx);S.locationData={orts:bundle.orts,sites:bundle.sites};S.supplyData={components};FP105.supplyRows=[{art:'Kraftstoff',richtung:'Aufnahme',menge:'',einheit:'l',kosten:'',waehrung:'EUR',komponenteId:'',notiz:''}];app.innerHTML=`<div class="card"><div class="fp-compact-time"><span><b>Ver- / Entsorgung</b><small>Zeitpunkt/GPS beim Cockpit-Tipp erfasst</small></span><span>${fp104Date(ctx.timestamp)} · ${fp104Time(ctx.timestamp)}</span></div>${fp105LocationBlock('su',bundle.orts,bundle.sites,bundle.near,'Ort / Standort')}<div class="fp-gps-read">GPS: ${ctx.lat!=null?`${ctx.lat.toFixed(6)} · ${ctx.lon.toFixed(6)}${ctx.accuracy?` · ± ${Math.round(ctx.accuracy)} m`:''}`:'nicht verfügbar'}</div><div class="section">Positionen</div><div id="fp105SupplyRows"></div><div class="fp105-supply-actions"><button type="button" onclick="fp105AddSupplyRow()">+ Position</button><b id="fp105SupplyTotal"></b></div><div class="field"><label>Gesamtnotiz optional</label><textarea id="supHeaderNote"></textarea></div><button class="primary" onclick="saveSupply105()">Ver-/Entsorgung speichern</button></div>`;fp105RefreshSites('su');fp105RenderSupplyRows();document.getElementById('fp105SupplyRows').addEventListener('input',fp105UpdateSupplyTotal)}catch(e){failBox(e)}
};
async function saveSupply105(){
  fp105SupplyReadRows();const rows=FP105.supplyRows.filter(r=>r.art);if(!rows.length)return alert('Mindestens eine Position erfassen.');
  try{const api=await getCloud(),ctx=fp105Ctx(),loc=fp105LocationValue('su'),currencies=[...new Set(rows.filter(r=>Number(r.kosten)>0).map(r=>r.waehrung||'EUR'))],currency=currencies.length===1?currencies[0]:'EUR',total=rows.reduce((a,r)=>a+Number(r.kosten||0),0),hf={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day?.id||''),Zeitpunkt:ctx.timestamp,OrtId:loc.ortId,StandortId:loc.standortId,GesamtKosten:total||null,Waehrung:currency,Notiz:supHeaderNote.value.trim(),Testdaten:testFlag(),Aktiv:true};if(ctx.lat!=null){hf.Breitengrad=ctx.lat;hf.Laengengrad=ctx.lon;if(ctx.accuracy!=null)hf.GenauigkeitM=ctx.accuracy}const h=await api.createItemByName('VerEntsorgungen',hf);let warnings=[];for(const r of rows){let ausgabeId='';if(Number(r.kosten)>0){try{const a=await api.createItemByName('Ausgaben',{FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),BezugTyp:'VerEntsorgung',BezugId:String(h.id),Kostenart:`${r.richtung}: ${r.art}`,Betrag:Number(r.kosten),Waehrung:r.waehrung||'EUR',Datum:ctx.timestamp,Startdatum:ctx.timestamp,IntervallArt:'Einmalig',Notiz:r.notiz||'',Aktiv:true,Testdaten:testFlag()});ausgabeId=String(a.id)}catch(e){warnings.push('Kostenposition konnte nicht zusätzlich in Ausgaben gespiegelt werden.')}}await api.createItemByName('VerEntsorgungsPositionen',{VorgangId:String(h.id),KomponenteId:String(r.komponenteId||''),Art:r.art,Richtung:r.richtung,Menge:r.menge!==''?Number(r.menge):null,Einheit:r.einheit||'',Kosten:r.kosten!==''?Number(r.kosten):null,Waehrung:r.waehrung||'EUR',AusgabeId:ausgabeId,Notiz:r.notiz||'',Testdaten:testFlag(),Aktiv:true})}await fp105RememberLocation(api,loc,ctx,'Ver-/Entsorgung',h.id);S.pendingContext=null;if(warnings.length)alert('Ver-/Entsorgung gespeichert. Hinweis: '+warnings[0]);back()}catch(e){alert('Ver-/Entsorgung konnte nicht gespeichert werden: '+e.message+'\nBitte Microsoft 365 Setup für Version 1.0.5 ausführen.')}
}
saveSupply=saveSupply105;

/* Online-Wetter: Standard ist automatischer Abruf. Manuelle Eingabe nur als Korrektur/Fallback. */
function fp105WeatherDesc(code){const m={0:'klar',1:'überwiegend klar',2:'teilweise bewölkt',3:'bedeckt',45:'Nebel',48:'Raureifnebel',51:'leichter Nieselregen',53:'Nieselregen',55:'starker Nieselregen',56:'gefrierender Nieselregen',57:'starker gefrierender Nieselregen',61:'leichter Regen',63:'Regen',65:'starker Regen',66:'gefrierender Regen',67:'starker gefrierender Regen',71:'leichter Schneefall',73:'Schneefall',75:'starker Schneefall',77:'Schneegriesel',80:'leichte Regenschauer',81:'Regenschauer',82:'starke Regenschauer',85:'leichte Schneeschauer',86:'starke Schneeschauer',95:'Gewitter',96:'Gewitter mit Hagel',99:'starkes Gewitter mit Hagel'};return m[Number(code)]||`Wettercode ${code}`}
function fp105WindDir(deg){if(deg==null||!Number.isFinite(Number(deg)))return'';const p=['N','NNO','NO','ONO','O','OSO','SO','SSO','S','SSW','SW','WSW','W','WNW','NW','NNW'];return p[Math.round(Number(deg)/22.5)%16]}
function fp105Set(id,v){const e=document.getElementById(id);if(e&&v!=null&&!Number.isNaN(v))e.value=v}
function fp105WeatherSummary(data){
  const parts=[];if(data.temp!=null)parts.push(`${data.temp} °C`);if(data.hum!=null)parts.push(`${data.hum} %`);if(data.press!=null)parts.push(`${data.press} hPa`);if(data.wind!=null)parts.push(`${data.dir||''} ${data.wind} km/h`.trim());if(data.gust!=null)parts.push(`Böen ${data.gust} km/h`);if(data.desc)parts.push(data.desc);return parts.join(' · ')
}
async function fp105FetchJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`Online-Dienst HTTP ${r.status}`);return r.json()}
async function fp105LoadWeatherOnline(){
  const st=document.getElementById('fp105WeatherStatus'),summary=document.getElementById('fp105WeatherSummary'),ctx=fp105Ctx(),lat=ctx.lat,lon=ctx.lon;if(lat==null||lon==null){if(st)st.innerHTML='<span class="status-warn">Kein GPS vorhanden – bitte manuell erfassen.</span>';return}
  if(st)st.textContent='Online-Wetter wird geladen …';
  try{
    const whenEl=document.getElementById('weWhen'),target=new Date(whenEl?.value?new Date(whenEl.value):ctx.timestamp),now=new Date(),diff=(target-now)/3600000,vars='temperature_2m,relative_humidity_2m,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,cloud_cover,precipitation,weather_code,visibility';let url='',d={};
    if(Math.abs(diff)<=3){
      url=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&current=${vars}&wind_speed_unit=kmh&timezone=GMT`;
      const j=await fp105FetchJson(url),c=j.current||{};d={temp:c.temperature_2m,hum:c.relative_humidity_2m,press:c.surface_pressure,wind:c.wind_speed_10m,windDeg:c.wind_direction_10m,gust:c.wind_gusts_10m,cloud:c.cloud_cover,rain:c.precipitation,code:c.weather_code,vis:c.visibility!=null?Number(c.visibility)/1000:null};
    }else{
      const date=target.toISOString().slice(0,10),historical=diff<0,base=historical?'https://archive-api.open-meteo.com/v1/archive':'https://api.open-meteo.com/v1/forecast',extra=historical?`start_date=${date}&end_date=${date}`:`forecast_days=16`;
      url=`${base}?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&${extra}&hourly=${vars}&wind_speed_unit=kmh&timezone=GMT`;
      const j=await fp105FetchJson(url),h=j.hourly||{},times=h.time||[];if(!times.length)throw new Error('Für diesen Zeitpunkt sind keine Online-Wetterdaten verfügbar.');let idx=0,best=Infinity;for(let i=0;i<times.length;i++){const delta=Math.abs(new Date(times[i]+'Z')-target);if(delta<best){best=delta;idx=i}}d={temp:h.temperature_2m?.[idx],hum:h.relative_humidity_2m?.[idx],press:h.surface_pressure?.[idx],wind:h.wind_speed_10m?.[idx],windDeg:h.wind_direction_10m?.[idx],gust:h.wind_gusts_10m?.[idx],cloud:h.cloud_cover?.[idx],rain:h.precipitation?.[idx],code:h.weather_code?.[idx],vis:h.visibility?.[idx]!=null?Number(h.visibility[idx])/1000:null};
    }
    d.dir=fp105WindDir(d.windDeg);d.desc=fp105WeatherDesc(d.code);fp105Set('weTemp',d.temp);fp105Set('weHum',d.hum);fp105Set('wePress',d.press);fp105Set('weWind',d.wind);fp105Set('weGust',d.gust);fp105Set('weCloud',d.cloud);fp105Set('weVis',d.vis!=null?Number(d.vis).toFixed(1):null);fp105Set('weDir',d.dir);fp105Set('weRain',d.rain!=null?`${d.rain} mm`:'');fp105Set('weDesc',d.desc);fp105Set('weCode',d.code);
    if(S.vehicle.profile==='motorboat'&&Math.abs(diff)<=3){try{const mu=`https://marine-api.open-meteo.com/v1/marine?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&current=wave_height,sea_surface_temperature&timezone=GMT`,mj=await fp105FetchJson(mu),mc=mj.current||{};fp105Set('weWave',mc.wave_height);fp105Set('weWater',mc.sea_surface_temperature)}catch(e){console.warn('Marine Wetterdaten nicht verfügbar',e)}}
    FP105.weatherSource={name:diff<-3?'Open-Meteo Historie':'Open-Meteo',url,fetchedAt:new Date().toISOString()};if(summary)summary.innerHTML=`<b>${esc(fp105WeatherSummary(d)||'Wetterdaten geladen')}</b>`;if(st)st.innerHTML=`Online geladen · Quelle: <b>${esc(FP105.weatherSource.name)}</b> · ${fp104Time(FP105.weatherSource.fetchedAt)} <a href="${esc(url)}" target="_blank" rel="noopener">Quelle öffnen</a>`;
  }catch(e){FP105.weatherSource=null;if(st)st.innerHTML=`<span class="status-warn">Online-Abruf nicht möglich: ${esc(e.message)} · Manuelle Eingabe bleibt verfügbar.</span>`}
}
weather=async function(){
  head('Wetter / Umweltbedingungen',S.vehicle.name);const ctx=fp105Ctx(),boat=S.vehicle.profile==='motorboat';
  try{const api=await getCloud(),bundle=await fp105LocationBundle(api,ctx);S.locationData={orts:bundle.orts,sites:bundle.sites};app.innerHTML=`<div class="card"><div class="fp-compact-time"><span><b>Wetter</b><small>GPS + Zeitpunkt automatisch</small></span><input id="weWhen" type="datetime-local" value="${fp105IsoLocalValue(ctx.timestamp)}"></div>${fp105LocationBlock('we',bundle.orts,bundle.sites,bundle.near,'Ort / Standort')}<div class="fp-gps-read">GPS: ${ctx.lat!=null?`${ctx.lat.toFixed(6)} · ${ctx.lon.toFixed(6)}${ctx.accuracy?` · ± ${Math.round(ctx.accuracy)} m`:''}`:'nicht verfügbar'}</div><div id="fp105WeatherSummary" class="fp105-weather-summary">Wetterdaten werden geladen …</div><div id="fp105WeatherStatus" class="muted"></div><div class="actions"><button type="button" onclick="fp105LoadWeatherOnline()">Online neu laden</button></div><details class="fp105-weather-manual"><summary>Manuell korrigieren / ergänzen</summary><div class="grid compact"><div class="field"><label>Temperatur °C</label><input id="weTemp" type="number" step="0.1"></div><div class="field"><label>Luftfeuchte %</label><input id="weHum" type="number" step="1"></div><div class="field"><label>Luftdruck hPa</label><input id="wePress" type="number" step="0.1"></div><div class="field"><label>Sichtweite km</label><input id="weVis" type="number" step="0.1"></div></div><div class="grid compact"><div class="field"><label>Windrichtung</label><input id="weDir"></div><div class="field"><label>Wind km/h</label><input id="weWind" type="number" step="0.1"></div><div class="field"><label>Böen km/h</label><input id="weGust" type="number" step="0.1"></div><div class="field"><label>Bewölkung %</label><input id="weCloud" type="number" step="1"></div></div><div class="grid compact"><div class="field"><label>Niederschlag</label><input id="weRain"></div>${boat?`<div class="field"><label>Wassertemperatur °C</label><input id="weWater" type="number" step="0.1"></div><div class="field"><label>Wellenhöhe m</label><input id="weWave" type="number" step="0.1"></div><div class="field"><label>Beaufort</label><input id="weBft" type="number" min="0" max="12"></div>`:''}</div>${boat?`<div class="field"><label>Seegang</label><input id="weSea"></div>`:''}<div class="field"><label>Wetterbeschreibung</label><textarea id="weDesc"></textarea></div><input id="weCode" type="hidden"></details><button class="primary" onclick="saveWeather105()">Wetter speichern</button></div>`;fp105RefreshSites('we');setTimeout(fp105LoadWeatherOnline,0)}catch(e){failBox(e)}
};
async function saveWeather105(){
  try{const api=await getCloud(),ctx=fp105Ctx(),loc=fp105LocationValue('we'),when=document.getElementById('weWhen')?.value?new Date(weWhen.value).toISOString():ctx.timestamp,num=id=>{const e=document.getElementById(id);return e&&e.value!==''?Number(e.value):null},f={FahrzeugId:String(S.vehicle.id),NutzungId:String(S.usage.cloudId),TagesetappeId:String(S.day.id),Zeitpunkt:when,OrtId:loc.ortId,StandortId:loc.standortId,Windrichtung:weDir.value.trim(),Niederschlag:weRain.value.trim(),Wetterbeschreibung:weDesc.value.trim(),Quelle:FP105.weatherSource?.name||'Manuell',AbrufAm:FP105.weatherSource?.fetchedAt||null,QuellURL:FP105.weatherSource?.url||'',Wettercode:num('weCode'),Testdaten:testFlag(),Aktiv:true};if(ctx.lat!=null){f.Breitengrad=ctx.lat;f.Laengengrad=ctx.lon;if(ctx.accuracy!=null)f.GenauigkeitM=ctx.accuracy}for(const [k,id] of [['Temperatur','weTemp'],['Luftfeuchte','weHum'],['Luftdruck','wePress'],['Sichtweite','weVis'],['Windgeschwindigkeit','weWind'],['Boeen','weGust'],['Bewoelkung','weCloud'],['Wassertemperatur','weWater'],['Wellenhoehe','weWave'],['Beaufort','weBft']]){const v=num(id);if(v!=null)f[k]=v}if(document.getElementById('weSea'))f.Seegang=weSea.value.trim();const x=await api.createItemByName('Wetterdaten',f);await fp105RememberLocation(api,loc,{...ctx,timestamp:when},'Wetter',x.id);S.pendingContext=null;back()}catch(e){alert('Wetter konnte nicht gespeichert werden: '+e.message+'\nBitte Microsoft 365 Setup für Version 1.0.5 ausführen.')}
}
saveWeather104=saveWeather105;

/* Fahrzeugbezogene Berechtigungsregeln vorbereiten. Straßenfahrzeuge können fest, Boote bedingungs-/revierabhängig hinterlegt werden. */
const fp105VehicleConfigureBase=vehicleconfigure;
vehicleconfigure=async function(){await fp105VehicleConfigureBase();await fp105AppendVehicleRules()};
async function fp105AppendVehicleRules(){
  if(!S.configVehicleId)return;try{const api=await getCloud(),rules=(await fp105SafeList(api,'FahrzeugBerechtigungsRegeln')).filter(x=>String(x.fields.FahrzeugId)===String(S.configVehicleId)&&x.fields.Aktiv!==false),box=document.createElement('div');box.className='card';box.id='sec-authrules';box.innerHTML=`<div class="section first">Fachliche Berechtigungen / Lizenzen</div><p class="muted">App-Rechte sind davon getrennt. Bei Booten dürfen Regeln ausdrücklich von Revier, Nutzung oder Ausrüstung abhängen.</p>${rules.map(r=>`<div class="line"><div><b>${esc(r.fields.NachweisArt||'Nachweis')}</b><div class="muted">${esc(r.fields.Regelart||'')} · ${esc(r.fields.Pflichtgrad||'Pflicht')}${r.fields.Bedingung?` · ${esc(r.fields.Bedingung)}`:''}</div></div><button class="danger-lite" onclick="fp105DeleteVehicleRule('${r.id}')">Löschen</button></div>`).join('')||'<p class="muted">Noch keine Regel hinterlegt.</p>'}<div class="subeditor"><div class="grid compact"><select id="arKind"><option>Fahrerlaubnis</option><option>Bootsfuehrerschein / Patent</option><option>Funkzeugnis</option><option>Sonderberechtigung</option><option>Sonstiges</option></select><input id="arProof" placeholder="Benötigter Nachweis, z. B. Führerschein Klasse B"><select id="arLevel"><option>Pflicht</option><option>Situativ</option><option>Empfohlen</option></select></div><div class="field"><label>Gilt bei / Bedingung</label><input id="arCondition" placeholder="z. B. Frankreich Binnen, Funkanlage wird benutzt, Wasserski"></div><button onclick="fp105AddVehicleRule()">Regel hinzufügen</button></div>`;app.appendChild(box)}catch(e){const box=document.createElement('div');box.className='card status-warn';box.textContent='Berechtigungsregeln werden nach dem Microsoft 365 Setup 1.0.5 verfügbar.';app.appendChild(box)}
}
async function fp105AddVehicleRule(){if(!arProof.value.trim())return alert('Benötigten Nachweis eingeben.');try{const api=await getCloud();await api.createItemByName('FahrzeugBerechtigungsRegeln',{FahrzeugId:String(S.configVehicleId),Regelart:arKind.value,NachweisArt:arProof.value.trim(),Bedingung:arCondition.value.trim(),Pflichtgrad:arLevel.value,Aktiv:true});rerenderKeepPosition('sec-authrules')}catch(e){alert(e.message)}}
async function fp105DeleteVehicleRule(id){if(!confirm('Berechtigungsregel löschen?'))return;try{const api=await getCloud();await api.deleteItemByName('FahrzeugBerechtigungsRegeln',id);rerenderKeepPosition('sec-authrules')}catch(e){alert(e.message)}}

/* Verleih: Tiere, App-Rechte und fachliche Berechtigung klar getrennt. */
function fp105LendingDefaultRights(){return ['Nutzung starten / fortsetzen','Cockpit bedienen','Messwerte / Ver-/Entsorgung erfassen','Kontrollen durchführen','Fotos / Medien hinzufügen']}
function fp105SplitRights(v){return String(v||'').split('|').map(x=>x.trim()).filter(Boolean)}
function fp105SyncLendingExtras(){S.lendSelectedAnimals=[...document.querySelectorAll('[data-lend-animal]:checked')].map(x=>String(x.dataset.lendAnimal));S.lendSelectedRights=[...document.querySelectorAll('[data-lend-right]:checked')].map(x=>String(x.dataset.lendRight))}
function fp105QualMatches(rule,personId){const q=(S.lendData?.quals||[]).filter(x=>String(x.fields.PersonId)===String(personId)&&x.fields.Aktiv!==false&&x.fields.Vorhanden!==false),need=fp105NormText(rule.fields.NachweisArt||'');return q.find(x=>{const art=fp105NormText(x.fields.Art||'');if(!(art.includes(need)||need.includes(art)))return false;if(x.fields.GueltigBis&&new Date(x.fields.GueltigBis)<new Date(document.getElementById('leFrom')?.value||Date.now()))return false;return true})}
function fp105LendingAuthHtml(vehicleId){const rules=(S.lendData?.rules||[]).filter(x=>String(x.fields.FahrzeugId)===String(vehicleId)&&x.fields.Aktiv!==false),borrowers=(S.lendSelected||[]).filter(x=>x.function==='Leiher');if(!rules.length)return '<p class="muted">Für dieses Fahrzeug sind noch keine fachlichen Berechtigungsregeln hinterlegt.</p>';return rules.map(r=>{if(r.fields.Pflichtgrad==='Situativ')return `<div class="fp105-auth-line"><b>🟡 ${esc(r.fields.NachweisArt)}</b><span>${esc(r.fields.Bedingung||'abhängig von Revier / Nutzung / Ausrüstung')} · im Reisecheck prüfen</span></div>`;if(!borrowers.length)return `<div class="fp105-auth-line"><b>🟡 ${esc(r.fields.NachweisArt)}</b><span>Noch kein Leiher ausgewählt.</span></div>`;const all=borrowers.every(b=>!!fp105QualMatches(r,b.personId));return `<div class="fp105-auth-line"><b>${all?'🟢':'🔴'} ${esc(r.fields.NachweisArt)}</b><span>${all?'passender gültiger Nachweis hinterlegt':'bei mindestens einem Leiher kein passender gültiger Nachweis gefunden'}${r.fields.Bedingung?` · ${esc(r.fields.Bedingung)}`:''}</span></div>`}).join('')}
const fp105DeleteLendingBase=deleteLending104;
deleteLending104=async function(id){if(!confirm('Vorbereitete Überlassung wirklich löschen?'))return;try{const api=await getCloud();for(const p of (S.lendData?.ups||[]).filter(x=>String(x.fields.UeberlassungId)===String(id)))await api.deleteItemByName('UeberlassungsPersonen',p.id);for(const a of (S.lendData?.uts||[]).filter(x=>String(x.fields.UeberlassungId)===String(id)))try{await api.deleteItemByName('UeberlassungsTiere',a.id)}catch{}await api.deleteItemByName('Fahrzeugueberlassungen',id);await lending()}catch(e){alert(e.message)}};
lending=async function(){
  head('Verleihmodus','Fahrzeugüberlassung · Personen, Tiere und App-Rechte');app.innerHTML='<div class="card">Verleihdaten werden geladen …</div>';
  try{const api=await getCloud(),[vs,ps,ls,ups,animals,uts,rules,quals]=await Promise.all([fp105SafeList(api,'Fahrzeuge'),fp105SafeList(api,'Personen'),fp105SafeList(api,'Fahrzeugueberlassungen'),fp105SafeList(api,'UeberlassungsPersonen'),fp105SafeList(api,'Tiere'),fp105SafeList(api,'UeberlassungsTiere'),fp105SafeList(api,'FahrzeugBerechtigungsRegeln'),fp105SafeList(api,'Befaehigungen')]);S.lendData={vs,ps,ls,ups,animals,uts,rules,quals};S.lendSelected=[];S.lendSelectedAnimals=[];S.lendSelectedRights=fp105LendingDefaultRights();const vm=Object.fromEntries(vs.map(x=>[String(x.id),x.fields.Fahrzeugname||x.fields.Title])),pm=Object.fromEntries(ps.map(x=>[String(x.id),x.fields.Anzeigename||x.fields.Title])),am=Object.fromEntries(animals.map(x=>[String(x.id),x.fields.Name||x.fields.Title])),normal=ls.filter(x=>!fp104LendingArchived(x)),archived=ls.filter(fp104LendingArchived),row=x=>{const members=ups.filter(p=>String(p.fields.UeberlassungId)===String(x.id)&&p.fields.Aktiv!==false),pets=uts.filter(a=>String(a.fields.UeberlassungId)===String(x.id)&&a.fields.Aktiv!==false).map(a=>am[String(a.fields.TierId)]).filter(Boolean),fallbackPets=fp105SplitRights(x.fields.TierIds).map(id=>am[id]).filter(Boolean),names=members.map(m=>esc(pm[String(m.fields.PersonId)]||'')).join(', ')||esc(pm[String(x.fields.LeiherPersonId)]||'');return `<div class="fp-lending-card"><div><b>${esc(vm[String(x.fields.FahrzeugId)]||'Fahrzeug')}</b><div>${names}</div>${(pets.length||fallbackPets.length)?`<div class="muted">Tiere: ${esc((pets.length?pets:fallbackPets).join(', '))}</div>`:''}<div class="muted">${fp104Date(x.fields.Beginn)} bis ${fp104Date(x.fields.Ende)} · ${esc(x.fields.Status||'')}</div></div><div class="row-actions">${fp104LendingActions(x)}</div></div>`};app.innerHTML=`<div class="card"><button class="primary" onclick="openNewLending()">Neue Überlassung</button></div><div class="card"><div class="section first">Vorhandene Überlassungen</div>${normal.map(row).join('')||'<p class="muted">Keine offenen Überlassungen.</p>'}<button onclick="toggleLendingArchive104()">Archiv / Auswertung (${archived.length})</button>${FP104.showLendingArchive?`<div class="section">Archiv</div>${archived.map(row).join('')||'<p class="muted">Archiv leer.</p>'}`:''}</div>`}catch(e){failBox(e)}
};
openNewLending=function(){S.editLendingId=null;S.lendSelected=[];S.lendSelectedAnimals=[];S.lendSelectedRights=fp105LendingDefaultRights();S.lendVehicleId=String(S.lendData?.vs?.find(v=>v.fields.Aktiv!==false)?.id||'');renderLendingEditor(null)};
editLending=function(id){S.editLendingId=String(id);const d=S.lendData,x=d.ls.find(v=>String(v.id)===String(id));S.lendVehicleId=String(x?.fields?.FahrzeugId||'');S.lendSelected=d.ups.filter(p=>String(p.fields.UeberlassungId)===String(id)&&p.fields.Aktiv!==false).map(p=>({personId:String(p.fields.PersonId),function:p.fields.Funktion||'Gast'}));const rel=d.uts.filter(a=>String(a.fields.UeberlassungId)===String(id)&&a.fields.Aktiv!==false).map(a=>String(a.fields.TierId)),fallback=fp105SplitRights(x?.fields?.TierIds);S.lendSelectedAnimals=rel.length?rel:fallback;S.lendSelectedRights=fp105SplitRights(x?.fields?.AppRechte||x?.fields?.Rechte);if(!S.lendSelectedRights.length)S.lendSelectedRights=fp105LendingDefaultRights();renderLendingEditor(x)};
addLendingPersonSelection=function(){fp105SyncLendingExtras();const id=leAddPerson.value;if(!id)return;const p=S.lendData.ps.find(x=>String(x.id)===String(id));S.lendSelected.push({personId:String(id),function:p.fields.Rolle==='Leiher'?'Leiher':'Gast'});renderLendingEditor(S.editLendingId?S.lendData.ls.find(x=>String(x.id)===String(S.editLendingId)):null)};
removeLendingPerson104=function(i){fp105SyncLendingExtras();S.lendSelected.splice(i,1);renderLendingEditor(S.editLendingId?S.lendData.ls.find(x=>String(x.id)===String(S.editLendingId)):null)};
function fp105LendingFunctionChanged(i,value){fp105SyncLendingExtras();if(S.lendSelected[i])S.lendSelected[i].function=value;renderLendingEditor(S.editLendingId?S.lendData.ls.find(x=>String(x.id)===String(S.editLendingId)):null)}
function fp105LendingVehicleChanged(){fp105SyncLendingExtras();S.lendVehicleId=String(document.getElementById('leVehicle')?.value||'');renderLendingEditor(S.editLendingId?S.lendData.ls.find(x=>String(x.id)===String(S.editLendingId)):null)}
renderLendingEditor=function(x){
  const d=S.lendData,selected=new Set((S.lendSelected||[]).map(x=>String(x.personId))),eligible=lendingEligiblePeople(),from=fp104LocalInput(x?.fields?.Beginn),to=fp104LocalInput(x?.fields?.Ende),vehicleId=String(S.lendVehicleId||x?.fields?.FahrzeugId||d.vs.find(v=>v.fields.Aktiv!==false)?.id||''),rights=['Nutzung starten / fortsetzen','Cockpit bedienen','Messwerte / Ver-/Entsorgung erfassen','Kontrollen durchführen','Fotos / Medien hinzufügen','Dokumente ansehen','Kosten ansehen'];
  app.innerHTML=`<div class="card"><div class="section first">${x?'Überlassung bearbeiten':'Neue Überlassung'}</div><div class="field"><label>Fahrzeug</label><select id="leVehicle" onchange="fp105LendingVehicleChanged()">${d.vs.filter(v=>v.fields.Aktiv!==false).map(v=>`<option value="${v.id}" ${String(vehicleId)===String(v.id)?'selected':''}>${esc(v.fields.Fahrzeugname||v.fields.Title)}</option>`).join('')}</select></div><div class="fp-pair"><div class="field"><label>Beginn</label><input id="leFrom" type="datetime-local" value="${from}"></div><div class="field"><label>Ende</label><input id="leTo" type="datetime-local" value="${to}"></div></div><div class="section">Personengruppe</div><div class="grid compact"><select id="leAddPerson"><option value="">– Leiher oder Gast auswählen –</option>${eligible.filter(p=>!selected.has(String(p.id))).map(p=>`<option value="${p.id}">${esc(p.fields.Anzeigename||p.fields.Title)} · ${esc(p.fields.Rolle)}</option>`).join('')}</select><button onclick="addLendingPersonSelection()">Person hinzufügen</button></div><div>${(S.lendSelected||[]).map((m,i)=>`<div class="line"><div>${esc((d.ps.find(p=>String(p.id)===String(m.personId))?.fields?.Anzeigename)||'')}</div><div class="row-actions"><select onchange="fp105LendingFunctionChanged(${i},this.value)"><option ${m.function==='Leiher'?'selected':''}>Leiher</option><option ${m.function==='Gast'?'selected':''}>Gast</option><option ${m.function==='Fahrer'?'selected':''}>Fahrer</option><option ${m.function==='Skipper'?'selected':''}>Skipper</option></select><button type="button" onclick="removeLendingPerson104(${i})">Entfernen</button></div></div>`).join('')||'<p class="muted">Noch niemand ausgewählt.</p>'}</div><div class="section">Mitfahrende Tiere</div>${d.animals.filter(a=>a.fields.Aktiv!==false).map(a=>`<label class="person-tile"><input type="checkbox" data-lend-animal="${a.id}" ${S.lendSelectedAnimals.includes(String(a.id))?'checked':''}> ${esc(a.fields.Name||a.fields.Title)} · ${esc(a.fields.Tierart||'')}</label>`).join('')||'<p class="muted">Keine Tiere im Tierstamm.</p>'}<div class="section">App-Rechte</div><p class="muted">Diese Rechte steuern nur, was die Gruppe in MOBIMORY bedienen darf. Führerschein, Patent oder andere fachliche Berechtigungen sind davon getrennt.</p>${rights.map(r=>`<label class="person-tile"><input type="checkbox" data-lend-right="${esc(r)}" ${S.lendSelectedRights.includes(r)?'checked':''}> ${esc(r)}</label>`).join('')}<div class="section">Fachliche Berechtigung</div><div id="fp105LendingAuth">${fp105LendingAuthHtml(vehicleId)}</div><div class="field"><label>Übergabenotiz / Zustand / Hinweise</label><textarea id="leNote">${esc(x?.fields?.UebergabeNotiz||'')}</textarea></div><button class="primary" onclick="saveLending105()">${x?'Änderungen speichern':'Überlassung anlegen'}</button></div>`;
};
async function saveLending105(){
  fp105SyncLendingExtras();if(!(S.lendSelected||[]).some(x=>x.function==='Leiher'))return alert('Mindestens eine Person muss als Leiher eingetragen sein.');if(!leFrom.value)return alert('Beginn eingeben.');
  try{const api=await getCloud(),primary=S.lendSelected.find(x=>x.function==='Leiher'),old=S.editLendingId?S.lendData.ls.find(x=>String(x.id)===String(S.editLendingId)):null,rights=(S.lendSelectedRights||[]).join('|'),fields={FahrzeugId:String(leVehicle.value),LeiherPersonId:String(primary.personId),Beginn:new Date(leFrom.value).toISOString(),Ende:leTo.value?new Date(leTo.value).toISOString():null,Status:old?.fields?.Status||'Vorbereitet',UebergabeNotiz:leNote.value.trim(),Gruppenmodus:true,TierIds:(S.lendSelectedAnimals||[]).join('|'),Rechte:rights,AppRechte:rights,Testdaten:testFlag(),Aktiv:old?.fields?.Aktiv===false?false:true};let id=S.editLendingId;if(id){await api.updateItemByName('Fahrzeugueberlassungen',id,fields);for(const o of S.lendData.ups.filter(x=>String(x.fields.UeberlassungId)===String(id)))await api.deleteItemByName('UeberlassungsPersonen',o.id);for(const o of S.lendData.uts.filter(x=>String(x.fields.UeberlassungId)===String(id)))try{await api.deleteItemByName('UeberlassungsTiere',o.id)}catch{}}else{id=String((await api.createItemByName('Fahrzeugueberlassungen',fields)).id)}for(const m of S.lendSelected)await api.createItemByName('UeberlassungsPersonen',{UeberlassungId:String(id),PersonId:String(m.personId),Funktion:m.function,Rechte:rights,QualifikationStatus:'zu prüfen',Aktiv:true,Testdaten:testFlag()});for(const tid of S.lendSelectedAnimals||[])try{await api.createItemByName('UeberlassungsTiere',{UeberlassungId:String(id),TierId:String(tid),Aktiv:true,Testdaten:testFlag()})}catch(e){console.warn('Tier-Relation nicht gespeichert, TierIds im Hauptdatensatz bleiben erhalten',e)}S.editLendingId=null;await lending()}catch(e){alert(e.message+'\nBitte Microsoft 365 Setup für Version 1.0.5 ausführen.')}
}
saveLending104=saveLending105;saveLending103=saveLending105;

/* M365 Setup 1.0.5: Basis + 1.0.4 + 1.0.5 additiv zusammenführen. */
function fp105MergeSchemas(...schemas){const map=new Map();for(const schema of schemas){for(const l of schema?.lists||[]){const k=l.internalName;if(!map.has(k))map.set(k,{...l,fields:[...(l.fields||[])]});else{const t=map.get(k),seen=new Set((t.fields||[]).map(f=>f.internalName));for(const f of l.fields||[])if(!seen.has(f.internalName)){t.fields.push(f);seen.add(f.internalName)}}}}return {...(schemas[0]||{}),version:'1.0.5',lists:[...map.values()]}}
async function fp105MergedSchema(){const [base,e104,e105]=await Promise.all([fetch('phase1-sharepoint-schema.json',{cache:'no-store'}).then(r=>r.json()),fetch('phase1-sharepoint-schema-1.0.4.json',{cache:'no-store'}).then(r=>r.json()),fetch('phase1-sharepoint-schema-1.0.5.json',{cache:'no-store'}).then(r=>r.json())]);return fp105MergeSchemas(base,e104,e105)}
m365setup=function(){head('Microsoft 365 Setup','Schema 1.0.5 · Phase 1 · additiv');const tok=window.FPAuth.token();app.innerHTML=`<div class="card"><b>Microsoft-Anmeldung</b><div id="authState">${tok?'✓ Microsoft-Token vorhanden':'Noch nicht mit Microsoft verbunden'}</div>${tok?'<button onclick="FPAuth.logout();render()">Microsoft-Verbindung trennen</button>':'<button class="primary" onclick="sessionStorage.setItem(\'fp_after_auth\',\'m365setup\');FPAuth.login()">Mit Microsoft 365 anmelden</button>'}</div><div class="card"><div class="field"><label>SharePoint-Site-URL</label><input id="spSite" value="${esc(localStorage.getItem('fp_sp_site')||'')}" placeholder="https://…sharepoint.com/sites/Fahrzeugplattform"></div><button class="primary" ${tok?'':'disabled'} onclick="runM365Provision105()">Phase-1-Struktur prüfen / anlegen</button><p class="muted">Additiv und wiederholbar. 1.0.5 ergänzt unter anderem Ortslernen, Ver-/Entsorgung, Tiere im Verleih und Berechtigungsregeln.</p></div><div id="m365Result"></div>`};
async function runM365Provision105(){const url=document.getElementById('spSite').value.trim();if(!url)return alert('Bitte die vollständige SharePoint-Site-URL eintragen.');localStorage.setItem('fp_sp_site',url);const out=document.getElementById('m365Result');out.innerHTML='<div class="card">Schema 1.0.5 wird geladen …</div>';try{const schema=await fp105MergedSchema(),setup=new FPGraphSetup(FPAuth.token(),url,schema),site=await setup.resolveSite();let lines=[];out.innerHTML=`<div class="card"><b>Verbunden:</b> ${esc(site.displayName)}<div id="provLog" class="muted">Prüfung startet …</div></div>`;const log=document.getElementById('provLog'),res=await setup.provision(e=>{if(e.status==='created')lines.push(`${e.kind==='list'?'Liste':'Feld'} angelegt: ${e.kind==='field'?e.list+' · ':''}${e.name}`);if(log)log.innerHTML=`Fortschritt: ${esc(e.kind==='field'?e.list+' · '+e.name:e.name)}<br>${lines.slice(-8).map(esc).join('<br>')}`});out.innerHTML=`<div class="card status-ok"><b>Setup abgeschlossen und verifiziert</b><p>${res.totalLists} Listen geprüft · ${res.listsCreated} neu angelegt · ${res.fieldsCreated} Felder neu angelegt · ${res.verifiedLists} Listen für die App erreichbar.</p></div>`}catch(e){out.innerHTML=`<div class="card status-stop"><b>Setup nicht abgeschlossen</b><p>${esc(e.message)}</p></div>`}}
runM365Provision=runM365Provision105;

exportPhase1Data=async function(){try{const schema=await fp105MergedSchema(),api=await getCloud(),data={exportedAt:new Date().toISOString(),version:FP105_VERSION,lists:{}};for(const l of schema.lists){try{data.lists[l.internalName]=await list(api,l.internalName)}catch(e){data.lists[l.internalName]={error:e.message}}}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Fahrzeugplattform_Export_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}};
clearTestData=async function(){if(!confirm('Alle als Testdaten markierten Bewegungs-/Vorgangsdaten wirklich löschen? Stammdaten bleiben erhalten.'))return;try{const api=await getCloud(),targets=['VerEntsorgungsPositionen','UeberlassungsTiere','PositionsOrtsHistorie','NutzungsPersonen','NutzungsTiere','NutzungsZwischenziele','Tagesetappen','Ereignisse','Aufenthalte','GPSPunkte','Messwerte','Versorgungsvorgaenge','VerEntsorgungen','Kontrollen','Arbeiten','Aufgaben','Pruefungen','Medien','Dokumente','Ausgaben','Wetterdaten','Fahrzeugueberlassungen','UeberlassungsPersonen','ReisecheckPunkte','Reisechecks','Stoerungen','Nutzungen'];let count=0;for(const ln of targets){let rows=[];try{rows=await list(api,ln)}catch{}for(const r of rows.filter(x=>x.fields.Testdaten===true)){try{await api.deleteItemByName(ln,r.id);count++}catch{}}}alert(`${count} Testdatensätze gelöscht.`)}catch(e){alert(e.message)}};

/* Responsive Ergänzungen. */
(()=>{const s=document.createElement('style');s.textContent=`
.fp105-location{margin:12px 0 18px}.fp105-loc-row{display:grid;grid-template-columns:1fr auto;gap:10px;margin:8px 0}.fp105-inline-new{display:grid;grid-template-columns:1fr auto auto;gap:8px;margin:8px 0 12px}.fp105-suggestion{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 12px;border:1px solid #ddd;border-radius:12px;margin:10px 0}.fp105-suggestion span{display:flex;flex-direction:column}.fp105-suggestion small{color:#666}.fp105-supply-row{border:1px solid #ddd;border-radius:14px;padding:14px;margin:10px 0}.fp105-row-head,.fp105-supply-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:10px}.fp105-weather-summary{font-size:1.15rem;padding:16px;border:1px solid #ddd;border-radius:14px;margin:12px 0}.fp105-weather-manual{margin:14px 0}.fp105-weather-manual summary{cursor:pointer;font-weight:700;padding:10px 0}.fp105-auth-line{display:flex;flex-direction:column;gap:3px;padding:9px 0;border-bottom:1px solid #eee}.fp105-auth-line:last-child{border-bottom:0}@media(max-width:620px){.fp105-inline-new{grid-template-columns:1fr}.fp105-suggestion{align-items:flex-start;flex-direction:column}.fp105-loc-row{grid-template-columns:1fr auto}}
`;document.head.appendChild(s)})();

/* Sichtbare Version. */
login=function(){bar.hidden=true;app.innerHTML=`<div class="login"><div class="card mobi-login">${typeof mobiIcon==='function'?mobiIcon():''}${typeof brandHeadline==='function'?brandHeadline():'<div class="brand">MOBIMORY</div>'}<p class="muted">Version ${FP105_VERSION}</p><div class="field"><label>Nutzer</label><input value="Admin"></div><div class="field"><label>Passwort</label><input type="password" value="admin"></div><button class="primary" onclick="S.stack=[];S.view='main';render()">Anmelden</button></div></div>`};
document.title=`Fahrzeugplattform ${FP105_VERSION}`;const fp105Foot=document.querySelector('footer');if(fp105Foot)fp105Foot.textContent=`Fahrzeugplattform · ${FP105_VERSION} · © 2026 Entwicklungsstand`;
try{render()}catch(e){console.warn(e)}
